const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const translations = {
  ar: {
    "Free": "مجاني",
    "Converter": "محول",
    "Text to Favicon": "نص إلى أيقونة",
    "Emoji to Favicon": "رمز تعبيري إلى أيقونة",
    "Favicon Checker": "فاحص الأيقونات",
    "Tutorials": "دروس تعليمية",
    "Blog": "المدونة",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "يدعم: PNG، JPG، SVG، WEBP، GIF (الحد الأقصى 5 ميجابايت)",
    "Output Sizes": "أحجام الإخراج",
    "Background Color (for transparent PNGs)": "لون الخلفية (لصور PNG الشفافة)",
    "Copy": "نسخ",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "ملف بيان تطبيق الويب يحتوي على مراجع الأيقونات، لون السمة، ولون الخلفية. ضروري لدعم PWA ودمج شاشة Android الرئيسية.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon مقابل الأدوات الأخرى في السوق",
    "See how we compare to other favicon generators on the market": "شاهد كيف نقارن بمولدات الأيقونات الأخرى في السوق",
    "Feature": "الميزة",
    "Other Tools": "أدوات أخرى",
    "Price": "السعر",
    "Free forever": "مجاني للأبد",
    "Freemium / Paid tiers": "مجاني جزئياً / مستويات مدفوعة",
    "Privacy": "الخصوصية",
    "100% Client-side": "100% من جانب العميل",
    "Files uploaded to servers": "يتم رفع الملفات إلى الخوادم",
    "Speed": "السرعة",
    "Instant processing": "معالجة فورية",
    "Depends on server load": "يعتمد على حمل الخادم",
    "File Formats": "تنسيقات الملفات",
    "ICO + PNG + Manifest": "ICO + PNG + بيان",
    "Often ICO only": "غالباً ICO فقط",
    "No Registration": "لا تسجيل",
    "No signup needed": "لا حاجة للتسجيل",
    "Sometimes required": "مطلوب أحياناً",
    "Multi-platform": "متعدد المنصات",
    "All devices & browsers": "جميع الأجهزة والمتصفحات",
    "Limited platform support": "دعم منصات محدود",
    "Testimonials": "آراء العملاء",
    "What Our Users Say": "ماذا يقول مستخدمونا",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "أكثر من 50,000 مطور ومصمم ومنشئ يثقون في PNGtoFavicon لمشاريعهم.",
    "from 500+ reviews": "من أكثر من 500 تقييم",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "أسرع طريقة لإنشاء جميع أحجام الأيقونات. يستغرق حرفياً ثانيتين ويتعامل مع تنسيقات manifest.json الجديدة بشكل مثالي.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "كنت أستخدم ImageMagick لهذا، لكن هذا الموقع أبسط بكثير. سحب وإفلات وتنزيل وانتهى الأمر.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "أحب أنه يعمل بالكامل في المتصفح. لست مضطراً للقلق بشأن تحميل شعارات العملاء الحساسة إلى خادم عشوائي.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "مثالي لتحويل صور PNG عالية الدقة إلى تنسيق ICO القديم. أداة لا بد منها لسير عمل تطوير الويب اليومي الخاص بي.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "واجهة مستخدم نظيفة، معالجة سريعة، ويمنحك علامات HTML الدقيقة للنسخ واللصق. أداة ممتازة!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "معالجة الشفافية دقيقة للغاية. المحولات الأخرى عادة ما تفسد قنوات ألفا، لكن هذا يعمل بشكل مثالي.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "أخيراً مولد أيقونات يتضمن أيقونة PWA بحجم 512x512. يوفر علي إعادة تغيير حجم الصور يدوياً.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "بسيط وفعال. واجهة الوضع المظلم لمسة لطيفة لنا نحن المطورين الذين نعمل في وقت متأخر من الليل.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "لقد حفظت هذا في الإشارات المرجعية. إنها أداة الأيقونات الوحيدة التي وجدتها والتي لا تمطرك بالإعلانات أو النوافذ المنبثقة.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "يولد أيقونات 16x16 واضحة بدون ضبابية. خوارزمية تغيير الحجم التي يستخدمونها هي بالتأكيد عالية الجودة.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "كمصمم تجربة مستخدم، أقدر الأدوات التي تعمل ببساطة. منطقة السحب والإفلات ضخمة ومتجاوبة.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "يعمل بشكل لا تشوبه شائبة على جهاز Mac الخاص بي. ملف zip الذي تم إنشاؤه منظم بشكل مثالي. موصى به للغاية.",
    "Frontend Developer": "مطور واجهات أمامية",
    "Web Designer": "مصمم ويب",
    "Software Engineer": "مهندس برمجيات",
    "UI/UX Designer": "مصمم واجهة وتجربة المستخدم",
    "Full Stack Dev": "مطور شامل",
    "Product Manager": "مدير منتج",
    "Indie Hacker": "مطور مستقل",
    "Tech Lead": "قائد تقني"
  },
  de: {
    "Free": "Kostenlos",
    "Converter": "Konverter",
    "Text to Favicon": "Text zu Favicon",
    "Emoji to Favicon": "Emoji zu Favicon",
    "Favicon Checker": "Favicon-Prüfer",
    "Tutorials": "Tutorials",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Unterstützt: PNG, JPG, SVG, WEBP, GIF (max. 5 MB)",
    "Output Sizes": "Ausgabegrößen",
    "Background Color (for transparent PNGs)": "Hintergrundfarbe (für transparente PNGs)",
    "Copy": "Kopieren",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Web-App-Manifest-Datei, die Symbolreferenzen, Designfarbe und Hintergrundfarbe enthält. Unverzichtbar für PWA-Unterstützung und Android-Startbildschirm-Integration.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon im Vergleich zu anderen Tools auf dem Markt",
    "See how we compare to other favicon generators on the market": "Sehen Sie, wie wir im Vergleich zu anderen Favicon-Generatoren auf dem Markt abschneiden",
    "Feature": "Funktion",
    "Other Tools": "Andere Tools",
    "Price": "Preis",
    "Free forever": "Für immer kostenlos",
    "Freemium / Paid tiers": "Freemium / Kostenpflichtig",
    "Privacy": "Datenschutz",
    "100% Client-side": "100% Clientseitig",
    "Files uploaded to servers": "Dateien werden auf Server hochgeladen",
    "Speed": "Geschwindigkeit",
    "Instant processing": "Sofortige Verarbeitung",
    "Depends on server load": "Hängt von der Serverlast ab",
    "File Formats": "Dateiformate",
    "ICO + PNG + Manifest": "ICO + PNG + Manifest",
    "Often ICO only": "Oft nur ICO",
    "No Registration": "Keine Registrierung",
    "No signup needed": "Keine Anmeldung erforderlich",
    "Sometimes required": "Manchmal erforderlich",
    "Multi-platform": "Multi-Plattform",
    "All devices & browsers": "Alle Geräte & Browser",
    "Limited platform support": "Eingeschränkte Plattformunterstützung",
    "Testimonials": "Referenzen",
    "What Our Users Say": "Was unsere Benutzer sagen",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Über 50.000 Entwickler, Designer und Ersteller vertrauen bei ihren Projekten auf PNGtoFavicon.",
    "from 500+ reviews": "aus 500+ Bewertungen",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Der schnellste Weg, alle Favicon-Größen zu generieren. Es dauert buchstäblich 2 Sekunden und verarbeitet die neuen manifest.json-Formate perfekt.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Ich habe früher ImageMagick dafür verwendet, aber diese Website ist so viel einfacher. Drag, Drop, Download, fertig.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Ich liebe es, dass es komplett im Browser läuft. Ich muss mir keine Sorgen machen, vertrauliche Kundenlogos auf irgendeinen Server hochzuladen.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Perfekt zum Konvertieren von hochauflösenden PNGs in das alte ICO-Format. Ein unverzichtbares Tool für meinen täglichen Web-Dev-Workflow.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Saubere Benutzeroberfläche, schnelle Verarbeitung und es gibt Ihnen die genauen HTML-Tags zum Kopieren und Einfügen. Ausgezeichnetes Tool!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "Die Transparenzbehandlung ist auf den Punkt. Andere Konverter bringen normalerweise die Alphakanäle durcheinander, aber dieser funktioniert perfekt.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Endlich ein Favicon-Generator, der das 512x512 PWA-Symbol enthält. Erspart mir die manuelle Größenänderung von Bildern.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Einfach und effektiv. Die Dark-Mode-Oberfläche ist eine nette Geste für uns Entwickler, die spät in der Nacht arbeiten.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Ich habe das mit einem Lesezeichen versehen. Es ist das einzige Favicon-Tool, das ich gefunden habe, das Sie nicht mit Werbung oder Popups bombardiert.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Generiert gestochen scharfe 16x16-Symbole ohne Unschärfe. Der von ihnen verwendete Skalierungsalgorithmus ist definitiv von hoher Qualität.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Als UX-Designer schätze ich Tools, die einfach funktionieren. Die Drag-and-Drop-Zone ist riesig und reaktionsschnell.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funktioniert einwandfrei auf meinem Mac. Die generierte Zip-Datei ist perfekt strukturiert. Sehr zu empfehlen.",
    "Frontend Developer": "Frontend-Entwickler",
    "Web Designer": "Webdesigner",
    "Software Engineer": "Softwareentwickler",
    "UI/UX Designer": "UI/UX-Designer",
    "Full Stack Dev": "Full-Stack-Entwickler",
    "Product Manager": "Produktmanager",
    "Indie Hacker": "Indie-Hacker",
    "Tech Lead": "Technischer Leiter"
  },
  es: {
    "Free": "Gratis",
    "Converter": "Convertidor",
    "Text to Favicon": "Texto a Favicon",
    "Emoji to Favicon": "Emoji a Favicon",
    "Favicon Checker": "Comprobador de Favicon",
    "Tutorials": "Tutoriales",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Soporta: PNG, JPG, SVG, WEBP, GIF (máx. 5MB)",
    "Output Sizes": "Tamaños de Salida",
    "Background Color (for transparent PNGs)": "Color de Fondo (para PNGs transparentes)",
    "Copy": "Copiar",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Archivo de manifiesto de aplicación web que contiene referencias de iconos, color de tema y color de fondo. Esencial para el soporte PWA y la integración en la pantalla de inicio de Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon frente a otras herramientas del mercado",
    "See how we compare to other favicon generators on the market": "Vea cómo nos comparamos con otros generadores de favicon del mercado",
    "Feature": "Característica",
    "Other Tools": "Otras Herramientas",
    "Price": "Precio",
    "Free forever": "Gratis para siempre",
    "Freemium / Paid tiers": "Freemium / Niveles de pago",
    "Privacy": "Privacidad",
    "100% Client-side": "100% Lado del cliente",
    "Files uploaded to servers": "Archivos subidos a servidores",
    "Speed": "Velocidad",
    "Instant processing": "Procesamiento instantáneo",
    "Depends on server load": "Depende de la carga del servidor",
    "File Formats": "Formatos de Archivo",
    "ICO + PNG + Manifest": "ICO + PNG + Manifiesto",
    "Often ICO only": "A menudo solo ICO",
    "No Registration": "Sin Registro",
    "No signup needed": "No se requiere registro",
    "Sometimes required": "A veces requerido",
    "Multi-platform": "Multiplataforma",
    "All devices & browsers": "Todos los dispositivos y navegadores",
    "Limited platform support": "Soporte de plataforma limitado",
    "Testimonials": "Testimonios",
    "What Our Users Say": "Lo que dicen nuestros usuarios",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Más de 50.000 desarrolladores, diseñadores y creadores confían en PNGtoFavicon para sus proyectos.",
    "from 500+ reviews": "de más de 500 reseñas",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "La forma más rápida de generar todos los tamaños de favicon. Literalmente toma 2 segundos y maneja perfectamente los nuevos formatos manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Solía ​​usar ImageMagick para esto, pero este sitio es mucho más simple. Arrastrar, soltar, descargar, listo.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Me encanta que se ejecute completamente en el navegador. No tengo que preocuparme por subir logotipos confidenciales de clientes a algún servidor aleatorio.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Perfecto para convertir PNG de alta resolución al formato ICO heredado. Una herramienta imprescindible para mi flujo de trabajo de desarrollo web diario.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interfaz de usuario limpia, procesamiento rápido y le brinda las etiquetas HTML exactas para copiar y pegar. ¡Excelente herramienta!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "El manejo de la transparencia es perfecto. Otros convertidores generalmente estropean los canales alfa, pero este funciona perfectamente.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Finalmente, un generador de favicons que incluye el ícono PWA de 512x512. Me ahorra la necesidad de cambiar el tamaño de las imágenes manualmente.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Sencillo y eficaz. La interfaz en modo oscuro es un buen detalle para nosotros, los desarrolladores que trabajamos hasta altas horas de la noche.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "He marcado esto como favorito. Es la única herramienta de favicon que he encontrado que no te bombardea con anuncios o ventanas emergentes.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Genera iconos nítidos de 16x16 sin desenfoque. El algoritmo de cambio de tamaño que utilizan es definitivamente de alta calidad.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Como diseñador de UX, aprecio las herramientas que simplemente funcionan. La zona de arrastrar y soltar es enorme y receptiva.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funciona impecablemente en mi Mac. El archivo zip generado está perfectamente estructurado. Muy recomendable.",
    "Frontend Developer": "Desarrollador Frontend",
    "Web Designer": "Diseñador Web",
    "Software Engineer": "Ingeniero de Software",
    "UI/UX Designer": "Diseñador UI/UX",
    "Full Stack Dev": "Desarrollador Full Stack",
    "Product Manager": "Gerente de Producto",
    "Indie Hacker": "Desarrollador Independiente",
    "Tech Lead": "Líder Técnico"
  },
  fr: {
    "Free": "Gratuit",
    "Converter": "Convertisseur",
    "Text to Favicon": "Texte en Favicon",
    "Emoji to Favicon": "Emoji en Favicon",
    "Favicon Checker": "Vérificateur de Favicon",
    "Tutorials": "Tutoriels",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Prend en charge : PNG, JPG, SVG, WEBP, GIF (max 5 Mo)",
    "Output Sizes": "Tailles de Sortie",
    "Background Color (for transparent PNGs)": "Couleur de Fond (pour PNG transparents)",
    "Copy": "Copier",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Fichier manifeste d'application Web contenant des références d'icônes, la couleur du thème et la couleur d'arrière-plan. Essentiel pour la prise en charge des PWA et l'intégration à l'écran d'accueil Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon par rapport aux autres outils du marché",
    "See how we compare to other favicon generators on the market": "Voyez comment nous nous comparons aux autres générateurs de favicon du marché",
    "Feature": "Fonctionnalité",
    "Other Tools": "Autres Outils",
    "Price": "Prix",
    "Free forever": "Gratuit pour toujours",
    "Freemium / Paid tiers": "Freemium / Niveaux payants",
    "Privacy": "Confidentialité",
    "100% Client-side": "100% Côté client",
    "Files uploaded to servers": "Fichiers téléchargés sur des serveurs",
    "Speed": "Vitesse",
    "Instant processing": "Traitement instantané",
    "Depends on server load": "Dépend de la charge du serveur",
    "File Formats": "Formats de Fichiers",
    "ICO + PNG + Manifest": "ICO + PNG + Manifeste",
    "Often ICO only": "Souvent ICO uniquement",
    "No Registration": "Pas d'Inscription",
    "No signup needed": "Aucune inscription nécessaire",
    "Sometimes required": "Parfois requis",
    "Multi-platform": "Multi-plateforme",
    "All devices & browsers": "Tous les appareils et navigateurs",
    "Limited platform support": "Prise en charge limitée des plateformes",
    "Testimonials": "Témoignages",
    "What Our Users Say": "Ce que disent nos utilisateurs",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Plus de 50 000 développeurs, designers et créateurs font confiance à PNGtoFavicon pour leurs projets.",
    "from 500+ reviews": "à partir de plus de 500 avis",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Le moyen le plus rapide de générer toutes les tailles de favicon. Cela prend littéralement 2 secondes et gère parfaitement les nouveaux formats manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "J'utilisais ImageMagick pour cela, mais ce site est tellement plus simple. Glisser, déposer, télécharger, terminé.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "J'adore qu'il s'exécute complètement dans le navigateur. Je n'ai pas à m'inquiéter de télécharger des logos clients sensibles sur un serveur aléatoire.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Parfait pour convertir des PNG haute résolution à l'ancien format ICO. Un outil indispensable pour mon flux de travail de développement Web quotidien.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interface utilisateur épurée, traitement rapide et vous donne les balises HTML exactes à copier-coller. Excellent outil !",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "La gestion de la transparence est parfaite. D'autres convertisseurs gâchent généralement les canaux alpha, mais celui-ci fonctionne parfaitement.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Enfin un générateur de favicon qui inclut l'icône PWA 512x512. M'évite de redimensionner manuellement les images.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Simple et efficace. L'interface en mode sombre est une touche agréable pour nous, développeurs travaillant tard le soir.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "J'ai mis cela dans mes favoris. C'est le seul outil de favicon que j'ai trouvé qui ne vous bombarde pas de publicités ou de popups.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Génère des icônes 16x16 nettes sans flou. L'algorithme de redimensionnement qu'ils utilisent est de très haute qualité.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "En tant que designer UX, j'apprécie les outils qui fonctionnent tout simplement. La zone de glisser-déposer est immense et réactive.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Fonctionne parfaitement sur mon Mac. Le fichier zip généré est parfaitement structuré. Hautement recommandé.",
    "Frontend Developer": "Développeur Frontend",
    "Web Designer": "Web Designer",
    "Software Engineer": "Ingénieur Logiciel",
    "UI/UX Designer": "Designer UI/UX",
    "Full Stack Dev": "Développeur Full Stack",
    "Product Manager": "Chef de Produit",
    "Indie Hacker": "Développeur Indépendant",
    "Tech Lead": "Responsable Technique"
  },
  id: {
    "Free": "Gratis",
    "Converter": "Konverter",
    "Text to Favicon": "Teks ke Favicon",
    "Emoji to Favicon": "Emoji ke Favicon",
    "Favicon Checker": "Pemeriksa Favicon",
    "Tutorials": "Tutorial",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Mendukung: PNG, JPG, SVG, WEBP, GIF (maks 5MB)",
    "Output Sizes": "Ukuran Output",
    "Background Color (for transparent PNGs)": "Warna Latar Belakang (untuk PNG transparan)",
    "Copy": "Salin",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "File Web App Manifest yang berisi referensi ikon, warna tema, dan warna latar belakang. Sangat penting untuk dukungan PWA dan integrasi layar beranda Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon vs Alat Lain di Pasaran",
    "See how we compare to other favicon generators on the market": "Lihat bagaimana kami dibandingkan dengan pembuat favicon lain di pasaran",
    "Feature": "Fitur",
    "Other Tools": "Alat Lainnya",
    "Price": "Harga",
    "Free forever": "Gratis selamanya",
    "Freemium / Paid tiers": "Freemium / Berbayar",
    "Privacy": "Privasi",
    "100% Client-side": "100% Sisi klien",
    "Files uploaded to servers": "File diunggah ke server",
    "Speed": "Kecepatan",
    "Instant processing": "Pemrosesan instan",
    "Depends on server load": "Tergantung pada beban server",
    "File Formats": "Format File",
    "ICO + PNG + Manifest": "ICO + PNG + Manifes",
    "Often ICO only": "Seringkali hanya ICO",
    "No Registration": "Tanpa Registrasi",
    "No signup needed": "Tidak perlu mendaftar",
    "Sometimes required": "Terkadang diperlukan",
    "Multi-platform": "Multi-platform",
    "All devices & browsers": "Semua perangkat & browser",
    "Limited platform support": "Dukungan platform terbatas",
    "Testimonials": "Testimoni",
    "What Our Users Say": "Apa Kata Pengguna Kami",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Lebih dari 50.000 pengembang, desainer, dan pembuat konten mempercayai PNGtoFavicon untuk proyek mereka.",
    "from 500+ reviews": "dari 500+ ulasan",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Cara tercepat untuk menghasilkan semua ukuran favicon. Secara harfiah membutuhkan waktu 2 detik dan menangani format manifest.json baru dengan sempurna.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Saya biasa menggunakan ImageMagick untuk ini, tetapi situs ini jauh lebih sederhana. Seret, lepas, unduh, selesai.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Suka karena berjalan sepenuhnya di browser. Saya tidak perlu khawatir mengunggah logo klien yang sensitif ke beberapa server acak.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Sempurna untuk mengonversi PNG resolusi tinggi ke format ICO lama. Alat yang harus dimiliki untuk alur kerja web dev harian saya.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "UI bersih, pemrosesan cepat, dan memberi Anda tag HTML persis untuk disalin-tempel. Alat luar biasa!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "Penanganan transparansi sangat tepat. Konverter lain biasanya mengacaukan saluran alpha, tetapi yang ini berfungsi dengan sempurna.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Akhirnya sebuah pembuat favicon yang menyertakan ikon PWA 512x512. Menyelamatkan saya dari mengubah ukuran gambar secara manual.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Sederhana dan efektif. Antarmuka mode gelap adalah sentuhan yang bagus untuk kami para pengembang yang bekerja hingga larut malam.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Saya telah menandai ini. Ini adalah satu-satunya alat favicon yang saya temukan yang tidak membombardir Anda dengan iklan atau popup.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Menghasilkan ikon 16x16 yang tajam tanpa keburaman. Algoritme pengubahan ukuran yang mereka gunakan pasti berkualitas tinggi.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Sebagai desainer UX, saya menghargai alat yang berfungsi begitu saja. Zona seret dan lepas sangat besar dan responsif.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Bekerja dengan sempurna di Mac saya. File zip yang dihasilkan terstruktur dengan sempurna. Sangat disarankan.",
    "Frontend Developer": "Pengembang Frontend",
    "Web Designer": "Desainer Web",
    "Software Engineer": "Insinyur Perangkat Lunak",
    "UI/UX Designer": "Desainer UI/UX",
    "Full Stack Dev": "Pengembang Full Stack",
    "Product Manager": "Manajer Produk",
    "Indie Hacker": "Peretas Indie",
    "Tech Lead": "Pemimpin Teknis"
  },
  pt: {
    "Free": "Gratuito",
    "Converter": "Conversor",
    "Text to Favicon": "Texto para Favicon",
    "Emoji to Favicon": "Emoji para Favicon",
    "Favicon Checker": "Verificador de Favicon",
    "Tutorials": "Tutoriais",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Suporta: PNG, JPG, SVG, WEBP, GIF (máx. 5MB)",
    "Output Sizes": "Tamanhos de Saída",
    "Background Color (for transparent PNGs)": "Cor de Fundo (para PNGs transparentes)",
    "Copy": "Copiar",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Arquivo de manifesto de aplicativo da Web contendo referências de ícones, cor de tema e cor de fundo. Essencial para suporte PWA e integração da tela inicial do Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon vs Outras Ferramentas no Mercado",
    "See how we compare to other favicon generators on the market": "Veja como nos comparamos a outros geradores de favicon no mercado",
    "Feature": "Recurso",
    "Other Tools": "Outras Ferramentas",
    "Price": "Preço",
    "Free forever": "Grátis para sempre",
    "Freemium / Paid tiers": "Freemium / Planos pagos",
    "Privacy": "Privacidade",
    "100% Client-side": "100% Lado do cliente",
    "Files uploaded to servers": "Arquivos carregados em servidores",
    "Speed": "Velocidade",
    "Instant processing": "Processamento instantâneo",
    "Depends on server load": "Depende da carga do servidor",
    "File Formats": "Formatos de Arquivo",
    "ICO + PNG + Manifest": "ICO + PNG + Manifesto",
    "Often ICO only": "Frequentemente apenas ICO",
    "No Registration": "Sem Registro",
    "No signup needed": "Sem necessidade de inscrição",
    "Sometimes required": "Às vezes necessário",
    "Multi-platform": "Multiplataforma",
    "All devices & browsers": "Todos os dispositivos e navegadores",
    "Limited platform support": "Suporte limitado à plataforma",
    "Testimonials": "Depoimentos",
    "What Our Users Say": "O que nossos usuários dizem",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Mais de 50.000 desenvolvedores, designers e criadores confiam no PNGtoFavicon para seus projetos.",
    "from 500+ reviews": "de mais de 500 avaliações",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "A maneira mais rápida de gerar todos os tamanhos de favicon. Literalmente leva 2 segundos e lida perfeitamente com os novos formatos manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Eu costumava usar o ImageMagick para isso, mas este site é muito mais simples. Arraste, solte, baixe, pronto.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Adoro que ele rode completamente no navegador. Não preciso me preocupar em enviar logotipos confidenciais de clientes para algum servidor aleatório.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Perfeito para converter PNGs de alta resolução para o formato ICO legado. Uma ferramenta obrigatória para o meu fluxo de trabalho diário de desenvolvimento da web.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interface de usuário limpa, processamento rápido e fornece as tags HTML exatas para copiar e colar. Excelente ferramenta!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "O manuseio da transparência é perfeito. Outros conversores costumam bagunçar os canais alfa, mas este funciona perfeitamente.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Finalmente um gerador de favicon que inclui o ícone PWA de 512x512. Me salva de redimensionar imagens manualmente.",
    "Simple and effective. The dark mode interface is a nice toque for us developers working late at night.": "Simples e eficaz. A interface do modo escuro é um toque agradável para nós, desenvolvedores que trabalhamos até tarde da noite.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Marquei isso nos favoritos. É a única ferramenta de favicon que encontrei que não o bombardeia com anúncios ou pop-ups.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Gera ícones nítidos de 16x16 sem desfoque. O algoritmo de redimensionamento que eles usam é definitivamente de alta qualidade.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Como designer de UX, aprecio ferramentas que simplesmente funcionam. A zona de arrastar e soltar é enorme e responsiva.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funciona perfeitamente no meu Mac. O arquivo zip gerado é perfeitamente estruturado. Altamente recomendado.",
    "Frontend Developer": "Desenvolvedor Frontend",
    "Web Designer": "Web Designer",
    "Software Engineer": "Engenheiro de Software",
    "UI/UX Designer": "Designer de UI/UX",
    "Full Stack Dev": "Desenvolvedor Full Stack",
    "Product Manager": "Gerente de Produto",
    "Indie Hacker": "Indie Hacker",
    "Tech Lead": "Líder Técnico"
  },
  tr: {
    "Free": "Ücretsiz",
    "Converter": "Dönüştürücü",
    "Text to Favicon": "Metinden Favicon'a",
    "Emoji to Favicon": "Emoji'den Favicon'a",
    "Favicon Checker": "Favicon Denetleyici",
    "Tutorials": "Öğreticiler",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Destekler: PNG, JPG, SVG, WEBP, GIF (maks 5MB)",
    "Output Sizes": "Çıktı Boyutları",
    "Background Color (for transparent PNGs)": "Arka Plan Rengi (şeffaf PNG'ler için)",
    "Copy": "Kopyala",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Simge referanslarını, tema rengini ve arka plan rengini içeren Web Uygulaması Bildirim dosyası. PWA desteği ve Android ana ekran entegrasyonu için gereklidir.",
    "PNGtoFavicon vs Other Tools in The Market": "Piyasadaki Diğer Araçlara Karşı PNGtoFavicon",
    "See how we compare to other favicon generators on the market": "Piyasadaki diğer favicon oluşturucularla nasıl karşılaştırdığımızı görün",
    "Feature": "Özellik",
    "Other Tools": "Diğer Araçlar",
    "Price": "Fiyat",
    "Free forever": "Sonsuza kadar ücretsiz",
    "Freemium / Paid tiers": "Freemium / Ücretli katmanlar",
    "Privacy": "Gizlilik",
    "100% Client-side": "%100 İstemci tarafı",
    "Files uploaded to servers": "Sunuculara yüklenen dosyalar",
    "Speed": "Hız",
    "Instant processing": "Anında işleme",
    "Depends on server load": "Sunucu yüküne bağlıdır",
    "File Formats": "Dosya Biçimleri",
    "ICO + PNG + Manifest": "ICO + PNG + Bildirim",
    "Often ICO only": "Genellikle sadece ICO",
    "No Registration": "Kayıt Yok",
    "No signup needed": "Kayıt gerekmez",
    "Sometimes required": "Bazen gerekli",
    "Multi-platform": "Çoklu platform",
    "All devices & browsers": "Tüm cihazlar ve tarayıcılar",
    "Limited platform support": "Sınırlı platform desteği",
    "Testimonials": "Referanslar",
    "What Our Users Say": "Kullanıcılarımız Ne Diyor",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "50.000'den fazla geliştirici, tasarımcı ve yaratıcı projeleri için PNGtoFavicon'a güveniyor.",
    "from 500+ reviews": "500'den fazla incelemeden",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Tüm favicon boyutlarını oluşturmanın en hızlı yolu. Kelimenin tam anlamıyla 2 saniye sürer ve yeni manifest.json formatlarını mükemmel şekilde işler.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Bunun için eskiden ImageMagick kullanıyordum ama bu site çok daha basit. Sürükle, bırak, indir, bitti.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Tamamen tarayıcıda çalışmasını seviyorum. Hassas müşteri logolarını rastgele bir sunucuya yükleme konusunda endişelenmeme gerek yok.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Yüksek çözünürlüklü PNG'leri eski ICO biçimine dönüştürmek için mükemmeldir. Günlük web geliştirme iş akışım için sahip olunması gereken bir araç.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Temiz kullanıcı arayüzü, hızlı işleme ve size kopyalayıp yapıştıracağınız tam HTML etiketlerini verir. Mükemmel bir araç!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "Şeffaflık işleme yerinde. Diğer dönüştürücüler genellikle alfa kanallarını bozar, ancak bu mükemmel çalışır.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Sonunda 512x512 PWA simgesini içeren bir favicon oluşturucu. Beni görüntüleri manuel olarak yeniden boyutlandırmaktan kurtarıyor.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Basit ve etkili. Karanlık mod arayüzü, gece geç saatlere kadar çalışan biz geliştiriciler için hoş bir dokunuş.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Bunu yer imlerine ekledim. Reklamlar veya açılır pencerelerle sizi bombardımana tutmayan bulduğum tek favicon aracı.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Bulanıklaştırmadan net 16x16 simgeler oluşturur. Kullandıkları yeniden boyutlandırma algoritması kesinlikle yüksek kalitededir.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Bir UX tasarımcısı olarak, sadece çalışan araçları takdir ediyorum. Sürükle ve bırak alanı devasa ve duyarlı.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Mac'imde kusursuz çalışıyor. Oluşturulan zip dosyası mükemmel şekilde yapılandırılmış. Şiddetle tavsiye edilir.",
    "Frontend Developer": "Frontend Geliştirici",
    "Web Designer": "Web Tasarımcı",
    "Software Engineer": "Yazılım Mühendisi",
    "UI/UX Designer": "UI/UX Tasarımcı",
    "Full Stack Dev": "Full Stack Geliştirici",
    "Product Manager": "Ürün Yöneticisi",
    "Indie Hacker": "Bağımsız Geliştirici",
    "Tech Lead": "Teknik Lider"
  },
  ur: {
    "Free": "مفت",
    "Converter": "کنورٹر",
    "Text to Favicon": "ٹیکسٹ سے فیویکن",
    "Emoji to Favicon": "ایموجی سے فیویکن",
    "Favicon Checker": "فیویکن چیکر",
    "Tutorials": "سبق",
    "Blog": "بلاگ",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "معاونت: PNG، JPG، SVG، WEBP، GIF (زیادہ سے زیادہ 5MB)",
    "Output Sizes": "آؤٹ پٹ سائز",
    "Background Color (for transparent PNGs)": "پس منظر کا رنگ (شفاف PNGs کے لیے)",
    "Copy": "کاپی",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "ویب ایپ مینی فیسٹ فائل جس میں آئیکن کے حوالہ جات، تھیم کا رنگ، اور پس منظر کا رنگ شامل ہے۔ PWA سپورٹ اور Android ہوم اسکرین کے انضمام کے لیے ضروری ہے۔",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon بمقابلہ مارکیٹ میں دیگر ٹولز",
    "See how we compare to other favicon generators on the market": "دیکھیں کہ ہم مارکیٹ میں موجود دیگر فیویکن جنریٹرز سے کیسے موازنہ کرتے ہیں۔",
    "Feature": "خصوصیت",
    "Other Tools": "دیگر ٹولز",
    "Price": "قیمت",
    "Free forever": "ہمیشہ کے لیے مفت",
    "Freemium / Paid tiers": "فریمیم / ادا شدہ درجات",
    "Privacy": "رازداری",
    "100% Client-side": "100% کلائنٹ سائیڈ",
    "Files uploaded to servers": "فائلیں سرورز پر اپ لوڈ کی گئیں۔",
    "Speed": "رفتار",
    "Instant processing": "فوری کارروائی",
    "Depends on server load": "سرور کے بوجھ پر منحصر ہے۔",
    "File Formats": "فائل فارمیٹس",
    "ICO + PNG + Manifest": "ICO + PNG + مینی فیسٹ",
    "Often ICO only": "اکثر صرف ICO",
    "No Registration": "کوئی رجسٹریشن نہیں۔",
    "No signup needed": "سائن اپ کی ضرورت نہیں۔",
    "Sometimes required": "بعض اوقات ضروری ہے۔",
    "Multi-platform": "ملٹی پلیٹ فارم",
    "All devices & browsers": "تمام آلات اور براؤزرز",
    "Limited platform support": "محدود پلیٹ فارم سپورٹ",
    "Testimonials": "تعریفیں",
    "What Our Users Say": "ہمارے صارفین کیا کہتے ہیں۔",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "50,000 سے زیادہ ڈویلپرز، ڈیزائنرز، اور تخلیق کار اپنے پروجیکٹس کے لیے PNGtoFavicon پر بھروسہ کرتے ہیں۔",
    "from 500+ reviews": "500+ جائزوں سے",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "تمام فیویکن سائز بنانے کا تیز ترین طریقہ۔ اس میں لفظی طور پر 2 سیکنڈ لگتے ہیں اور نئے manifest.json فارمیٹس کو بالکل ہینڈل کرتا ہے۔",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "میں اس کے لیے ImageMagick استعمال کرتا تھا، لیکن یہ سائٹ بہت آسان ہے۔ گھسیٹیں، چھوڑیں، ڈاؤن لوڈ کریں، ہو گیا۔",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "مجھے پسند ہے کہ یہ مکمل طور پر براؤزر میں چلتا ہے۔ مجھے حساس کلائنٹ کے لوگو کو کسی بے ترتیب سرور پر اپ لوڈ کرنے کی فکر کرنے کی ضرورت نہیں ہے۔",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "ہائی ریزولوشن PNGs کو پرانے ICO فارمیٹ میں تبدیل کرنے کے لیے بہترین ہے۔ میرے یومیہ ویب دیو ورک فلو کے لیے ایک لازمی ٹول۔",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "کلین UI، تیز پروسیسنگ، اور یہ آپ کو کاپی پیسٹ کرنے کے لیے درست HTML ٹیگز دیتا ہے۔ بہترین ٹول!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "شفافیت سے نمٹنے کا طریقہ بالکل درست ہے۔ دوسرے کنورٹرز عام طور پر الفا چینلز کو گڑبڑ کرتے ہیں، لیکن یہ بالکل کام کرتا ہے۔",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "آخر کار ایک فیویکن جنریٹر جس میں 512x512 PWA آئیکن شامل ہے۔ مجھے دستی طور پر تصاویر کا سائز تبدیل کرنے سے بچاتا ہے۔",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "سادہ اور موثر۔ ڈارک موڈ انٹرفیس ہم ڈویلپرز کے لیے ایک اچھا ٹچ ہے جو رات گئے کام کر رہے ہیں۔",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "میں نے اسے بک مارک کر لیا ہے۔ یہ واحد فیویکن ٹول ہے جو مجھے ملا ہے جو آپ پر اشتہارات یا پاپ اپس کی بمباری نہیں کرتا ہے۔",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "دھندلا کیے بغیر کرکرا 16x16 آئیکنز تیار کرتا ہے۔ ان کا استعمال کرنے والا نیا سائز دینے والا الگورتھم یقینی طور پر اعلیٰ معیار کا ہے۔",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "UX ڈیزائنر کے طور پر، میں ان ٹولز کی تعریف کرتا ہوں جو صرف کام کرتے ہیں۔ ڈریگ اور ڈراپ زون بہت بڑا اور جوابدہ ہے۔",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "میرے میک پر بے عیب کام کرتا ہے۔ تیار کردہ زپ فائل بالکل ساختہ ہے۔ انتہائی سفارش کی جاتی ہے.",
    "Frontend Developer": "فرنٹ اینڈ ڈویلپر",
    "Web Designer": "ویب ڈیزائنر",
    "Software Engineer": "سافٹ ویئر انجینئر",
    "UI/UX Designer": "UI/UX ڈیزائنر",
    "Full Stack Dev": "فل اسٹیک دیو",
    "Product Manager": "پروڈکٹ مینیجر",
    "Indie Hacker": "انڈی ہیکر",
    "Tech Lead": "ٹیک لیڈ"
  }
};

Object.keys(translations).forEach(lang => {
  const filePath = path.join(__dirname, lang, 'index.html');
  if (fs.existsSync(filePath)) {
    const html = fs.readFileSync(filePath, 'utf8');
    const dom = new JSDOM(html);
    const document = dom.window.document;
    const dict = translations[lang];

    // Replace text in all elements
    const walk = document.createTreeWalker(document.body, 4, null, false);
    let n;
    while ((n = walk.nextNode())) {
      const txt = n.nodeValue.trim();
      
      // Remove wrapping quotes for testimonials matching
      const txtUnquoted = txt.replace(/^"|"$/g, '');
      
      if (dict[txt]) {
        n.nodeValue = n.nodeValue.replace(txt, dict[txt]);
      } else if (dict[txtUnquoted]) {
        n.nodeValue = n.nodeValue.replace(txtUnquoted, dict[txtUnquoted]);
      } else if (txt === "Free forever" && n.parentNode && n.parentNode.innerHTML.includes("Free forever")) {
         n.nodeValue = n.nodeValue.replace("Free forever", dict["Free forever"]);
      }
    }
    
    // Specific fix for "Add this to your website's <head> tag:" which is mixed content
    document.querySelectorAll('p').forEach(p => {
      if (p.innerHTML.includes("Add this to your website's")) {
        const spanText = p.innerHTML;
        // Depending on language, replacing it differently, or just a simple regex to replace the string around <code>
        // For Arabic: أضف هذا إلى علامة <head> الخاصة بموقعك:
        // For German: Fügen Sie dies dem <head>-Tag Ihrer Website hinzu:
        // For Spanish: Añade esto a la etiqueta <head> de tu sitio web:
        // For French: Ajoutez ceci à la balise <head> de votre site Web :
        // For Indonesian: Tambahkan ini ke tag <head> situs web Anda:
        // For Portuguese: Adicione isso à tag <head> do seu site:
        // For Turkish: Bunu web sitenizin <head> etiketine ekleyin:
        // For Urdu: اسے اپنی ویب سائٹ کے <head> ٹیگ میں شامل کریں:
        
        let beforeTag = "";
        let afterTag = "";
        
        if (lang === 'ar') { beforeTag = "أضف هذا إلى علامة "; afterTag = " الخاصة بموقعك:"; }
        if (lang === 'de') { beforeTag = "Fügen Sie dies dem "; afterTag = "-Tag Ihrer Website hinzu:"; }
        if (lang === 'es') { beforeTag = "Añade esto a la etiqueta "; afterTag = " de tu sitio web:"; }
        if (lang === 'fr') { beforeTag = "Ajoutez ceci à la balise "; afterTag = " de votre site Web :"; }
        if (lang === 'id') { beforeTag = "Tambahkan ini ke tag "; afterTag = " situs web Anda:"; }
        if (lang === 'pt') { beforeTag = "Adicione isso à tag "; afterTag = " do seu site:"; }
        if (lang === 'tr') { beforeTag = "Bunu web sitenizin "; afterTag = " etiketine ekleyin:"; }
        if (lang === 'ur') { beforeTag = "اسے اپنی ویب سائٹ کے "; afterTag = " ٹیگ میں شامل کریں:"; }
        
        if (beforeTag) {
          p.innerHTML = `${beforeTag}<code>&lt;head&gt;</code>${afterTag}`;
        }
      }
    });

    fs.writeFileSync(filePath, dom.serialize(), 'utf8');
    console.log(`Fully translated ${lang}/index.html`);
  }
});
