const fs = require('fs');
const path = require('path');
const { JSDOM } = require('jsdom');

const translations = {
  ar: {
    "Free": "مجاني",
    "Converter": "محول",
    "Text to Favicon": "نص إلى أيقونة",
    "Emoji to Favicon": "رمز تعبيري إلى أيقونة",
    "Favicon Checker": "فاحص الأيقونات",
    "Tutorials": "دروس تعليمية",
    "Blog": "المدونة",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "يدعم: PNG، JPG، SVG، WEBP، GIF (الحد الأقصى 5 ميجابايت)",
    "Output Sizes": "أحجام الإخراج",
    "Background Color (for transparent PNGs)": "لون الخلفية (لصور PNG الشفافة)",
    "Copy": "نسخ",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "ملف بيان تطبيق الويب يحتوي على مراجع الأيقونات، لون السمة، ولون الخلفية. ضروري لدعم PWA ودمج شاشة Android الرئيسية.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon مقابل الأدوات الأخرى في السوق",
    "See how we compare to other favicon generators on the market": "شاهد كيف نقارن بمولدات الأيقونات الأخرى في السوق",
    "Feature": "الميزة",
    "Other Tools": "أدوات أخرى",
    "Price": "السعر",
    "Free forever": "مجاني للأبد",
    "Freemium / Paid tiers": "مجاني جزئياً / مستويات مدفوعة",
    "Privacy": "الخصوصية",
    "100% Client-side": "100% من جانب العميل",
    "Files uploaded to servers": "يتم رفع الملفات إلى الخوادم",
    "Speed": "السرعة",
    "Instant processing": "معالجة فورية",
    "Depends on server load": "يعتمد على حمل الخادم",
    "File Formats": "تنسيقات الملفات",
    "ICO + PNG + Manifest": "ICO + PNG + بيان",
    "Often ICO only": "غالباً ICO فقط",
    "No Registration": "لا تسجيل",
    "No signup needed": "لا حاجة للتسجيل",
    "Sometimes required": "مطلوب أحياناً",
    "Multi-platform": "متعدد المنصات",
    "All devices & browsers": "جميع الأجهزة والمتصفحات",
    "Limited platform support": "دعم منصات محدود",
    "Testimonials": "آراء العملاء",
    "What Our Users Say": "ماذا يقول مستخدمونا",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "أكثر من 50,000 مطور ومصمم ومنشئ يثقون في PNGtoFavicon لمشاريعهم.",
    "from 500+ reviews": "من أكثر من 500 تقييم",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "أسرع طريقة لإنشاء جميع أحجام الأيقونات. يستغرق حرفياً ثانيتين ويتعامل مع تنسيقات manifest.json الجديدة بشكل مثالي.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "كنت أستخدم ImageMagick لهذا، لكن هذا الموقع أبسط بكثير. سحب وإفلات وتنزيل وانتهى الأمر.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "أحب أنه يعمل بالكامل في المتصفح. لست مضطراً للقلق بشأن تحميل شعارات العملاء الحساسة إلى خادم عشوائي.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "مثالي لتحويل صور PNG عالية الدقة إلى تنسيق ICO القديم. أداة لا بد منها لسير عمل تطوير الويب اليومي الخاص بي.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "واجهة مستخدم نظيفة، معالجة سريعة، ويمنحك علامات HTML الدقيقة للنسخ واللصق. أداة ممتازة!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "معالجة الشفافية دقيقة للغاية. المحولات الأخرى عادة ما تفسد قنوات ألفا، لكن هذا يعمل بشكل مثالي.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "أخيراً مولد أيقونات يتضمن أيقونة PWA بحجم 512x512. يوفر علي إعادة تغيير حجم الصور يدوياً.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "بسيط وفعال. واجهة الوضع المظلم لمسة لطيفة لنا نحن المطورين الذين نعمل في وقت متأخر من الليل.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "لقد حفظت هذا في الإشارات المرجعية. إنها أداة الأيقونات الوحيدة التي وجدتها والتي لا تمطرك بالإعلانات أو النوافذ المنبثقة.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "يولد أيقونات 16x16 واضحة بدون ضبابية. خوارزمية تغيير الحجم التي يستخدمونها هي بالتأكيد عالية الجودة.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "كمصمم تجربة مستخدم، أقدر الأدوات التي تعمل ببساطة. منطقة السحب والإفلات ضخمة ومتجاوبة.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "يعمل بشكل لا تشوبه شائبة على جهاز Mac الخاص بي. ملف zip الذي تم إنشاؤه منظم بشكل مثالي. موصى به للغاية.",
    "Frontend Developer": "مطور واجهات أمامية",
    "Web Designer": "مصمم ويب",
    "Software Engineer": "مهندس برمجيات",
    "UI/UX Designer": "مصمم واجهة وتجربة المستخدم",
    "Full Stack Dev": "مطور شامل",
    "Product Manager": "مدير منتج",
    "Indie Hacker": "مطور مستقل",
    "Tech Lead": "قائد تقني"
  },
  de: {
    // Metadata / SEO
    "PNG to Favicon Converter — Free Online Tool | PNGtoFavicon": "PNG in Favicon umwandeln — Kostenloser Online-Konverter | PNGtoFavicon",
    "Convert PNG to favicon.ico instantly. Free online tool generates favicon.ico, apple-touch-icon, android icons, site.webmanifest & HTML code. 100% client-side — your files never leave the browser.": "Konvertieren Sie PNG sofort in favicon.ico. Das kostenlose Online-Tool erstellt favicon.ico, Apple-Touch-Icons, Android-Symbole, site.webmanifest und HTML-Code. 100% clientseitig — Ihre Bilder verlassen nie den Browser.",
    "png to favicon, favicon generator, png to ico, favicon converter, free favicon generator, online favicon maker": "png in favicon, favicon generator, png in ico, favicon konverter, favicon erstellen kostenlos, favicon online erstellen",
    "Convert PNG to favicon.ico instantly. Free online tool generates all favicon files. 100% client-side.": "Konvertieren Sie PNG sofort in favicon.ico. Das kostenlose Online-Tool generiert alle Favicon-Dateien. 100% clientseitig.",
    "PNG to Favicon Converter — Free Online Tool": "PNG in Favicon umwandeln — Kostenloser Online-Konverter",
    "Convert PNG to favicon.ico instantly. 100% free, 100% client-side.": "Konvertieren Sie PNG sofort in favicon.ico. 100% kostenlos und clientseitig.",

    // Dropzone / File upload UI & messages
    "Drag & drop your PNG image here": "Ziehen Sie Ihr PNG-Bild hierher (Drag & Drop)",
    "Upload area. Drag and drop your PNG image here or click to browse files.": "Upload-Bereich. Ziehen Sie Ihr PNG-Bild hierher oder klicken Sie, um Dateien zu durchsuchen.",
    "or click to browse files": "oder klicken Sie, um Dateien zu durchsuchen",
    "Choose File": "Datei auswählen",
    "Converting...": "Wird konvertiert...",
    "Download Favicon Pack": "Favicon-Paket herunterladen",
    "Generating...": "Wird generiert...",
    "Error loading image. Please try again.": "Fehler beim Laden des Bildes. Bitte versuchen Sie es erneut.",
    "Please upload a valid PNG image.": "Bitte laden Sie ein gültiges PNG-Bild hoch.",
    "File size exceeds 5MB limit.": "Die Dateigröße überschreitet das Limit von 5 MB.",

    // Navigation & Common
    "Free": "Kostenlos",
    "Converter": "Konverter",
    "Text to Favicon": "Text zu Favicon",
    "Emoji to Favicon": "Emoji zu Favicon",
    "Favicon Checker": "Favicon-Prüfer",
    "Tutorials": "Tutorials",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Unterstützt: PNG, JPG, SVG, WEBP, GIF (max. 5 MB)",
    "Output Sizes": "Ausgabegrößen",
    "Background Color (for transparent PNGs)": "Hintergrundfarbe (für transparente PNGs)",
    "Copy": "Kopieren",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Web-App-Manifest-Datei, die Symbolreferenzen, Designfarbe und Hintergrundfarbe enthält. Unverzichtbar für PWA-Unterstützung und Android-Startbildschirm-Integration.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon im Vergleich zu anderen Tools auf dem Markt",
    "See how we compare to other favicon generators on the market": "Sehen Sie, wie wir im Vergleich zu anderen Favicon-Generatoren auf dem Markt abschneiden",
    "Feature": "Funktion",
    "Other Tools": "Andere Tools",
    "Price": "Preis",
    "Free forever": "Für immer kostenlos",
    "Freemium / Paid tiers": "Freemium / Kostenpflichtig",
    "Privacy": "Datenschutz",
    "100% Client-side": "100% Clientseitig",
    "Files uploaded to servers": "Dateien werden auf Server hochgeladen",
    "Speed": "Geschwindigkeit",
    "Instant processing": "Sofortige Verarbeitung",
    "Depends on server load": "Hängt von der Serverlast ab",
    "File Formats": "Dateiformate",
    "ICO + PNG + Manifest": "ICO + PNG + Manifest",
    "Often ICO only": "Oft nur ICO",
    "No Registration": "Keine Registrierung",
    "No signup needed": "Keine Anmeldung erforderlich",
    "Sometimes required": "Manchmal erforderlich",
    "Multi-platform": "Multi-Plattform",
    "All devices & browsers": "Alle Geräte & Browser",
    "Limited platform support": "Eingeschränkte Plattformunterstützung",

    // Persona / Audience targeting
    "UI/UX Designers": "UI/UX-Designer",
    "Ensure your brand identity looks crisp and perfect across all browser tabs and device home screens.": "Stellen Sie sicher, dass Ihr Markenauftritt auf allen Browser-Tabs und Startbildschirmen gestochen scharf und perfekt aussieht.",
    "Bloggers & Creators": "Blogger & Content Creator",
    "Easily customize your personal blog or portfolio with a professional icon in seconds.": "Passen Sie Ihren persönlichen Blog oder Ihr Portfolio in Sekundenschnelle mit einem professionellen Icon an.",
    "Business Owners": "Unternehmen & Gründer",
    "Elevate your professional appearance with a high-quality favicon that builds trust.": "Werten Sie Ihren professionellen Auftritt mit einem hochwertigen Favicon auf, das Vertrauen schafft.",
    "Trusted by professionals worldwide": "Weltweit von Profis geschätzt",

    // File Downloads list
    "What's Included in Your Download": "Was in Ihrem Download enthalten ist",
    "Every file you need for full cross-browser and cross-device favicon support": "Jede Datei, die Sie für die vollständige Favicon-Kompatibilität auf allen Browsern und Geräten benötigen",
    "ICO": "ICO",
    "favicon.ico": "favicon.ico",
    "The classic multi-size ICO format, containing 16×16, 32×32, and 48×48 icons. Required for legacy browser support including older versions of Internet Explorer.": "Das klassische ICO-Format mit mehreren Größen (16×16, 32×32 und 48×48 Pixel). Erforderlich zur Unterstützung älterer Browser wie dem Internet Explorer.",
    "favicon-16x16.png": "favicon-16x16.png",
    "Standard browser tab icon at 16×16 pixels. Used by most modern browsers as the primary tab favicon for standard-density displays.": "Standard-Icon für Browser-Tabs mit 16×16 Pixeln. Wird von den meisten modernen Browsern als primäres Tab-Favicon für Standard-Displays verwendet.",
    "favicon-32x32.png": "favicon-32x32.png",
    "High-DPI browser tab icon at 32×32 pixels. Displayed on Retina and HiDPI screens for crisp, sharp favicon rendering in browser tabs.": "High-DPI-Icon für Browser-Tabs mit 32×32 Pixeln. Wird auf Retina- und HiDPI-Bildschirmen für eine gestochen scharfe Darstellung in Browser-Tabs angezeigt.",
    "apple-touch-icon.png": "apple-touch-icon.png",
    "Apple Touch Icon at 180×180 pixels for iPhone, iPad, and iPod Touch. Displayed when users add your website to their iOS home screen.": "Apple-Touch-Icon mit 180×180 Pixeln für iPhone und iPad. Wird angezeigt, wenn Benutzer Ihre Website zu ihrem iOS-Startbildschirm hinzufügen.",
    "android-chrome-192x192.png": "android-chrome-192x192.png",
    "Android home screen icon at 192×192 pixels. Used when Android users add your site to their home screen via Chrome or other browsers.": "Symbol für den Android-Startbildschirm mit 192×192 Pixeln. Wird verwendet, wenn Android-Nutzer Ihre Website über Chrome oder andere Browser zum Startbildschirm hinzufügen.",
    "android-chrome-512x512.png": "android-chrome-512x512.png",
    "High-resolution PWA icon at 512×512 pixels. Required for Progressive Web App install prompts and splash screens on Android devices.": "Hochauflösendes PWA-Icon mit 512×512 Pixeln. Erforderlich für PWA-Installationsaufforderungen und Splash-Screens auf Android-Geräten.",
    "JSON": "JSON",
    "site.webmanifest": "site.webmanifest",
    "PNGtoFavicon": "PNGtoFavicon",
    "HTML Code Snippet": "HTML-Code-Snippet",
    "Auto-generated": "Automatisch generiert",
    "Manual integration": "Manuelle Integration",
    "Open Source": "Open Source",
    "Transparent process": "Transparenter Prozess",
    "Proprietary black-box": "Proprietäre Blackbox",
    "4.9": "4.9",
    "Verified reviews on Trustpilot": "Verifizierte Bewertungen auf Trustpilot",
    "Verified reviews on Capterra": "Verifizierte Bewertungen auf Capterra",
    "Trustpilot": "Trustpilot",
    "Capterra": "Capterra",

    // Testimonials
    "Testimonials": "Referenzen",
    "What Our Users Say": "Was unsere Benutzer sagen",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Über 50.000 Entwickler, Designer und Ersteller vertrauen bei ihren Projekten auf PNGtoFavicon.",
    "from 500+ reviews": "aus 500+ Bewertungen",
    "Alex M.": "Alex M.",
    "Oct 2025": "Okt. 2025",
    "\"The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.\"": "\"Der schnellste Weg, alle Favicon-Größen zu generieren. Es dauert buchstäblich 2 Sekunden und verarbeitet die neuen manifest.json-Formate perfekt.\"",
    "Sarah J.": "Sarah J.",
    "Sep 2025": "Sept. 2025",
    "\"I used to use 3 different tools to get my PNG converted into an ICO and Apple Touch Icons. This does it all in one click.\"": "\"Früher habe ich drei verschiedene Tools verwendet, um mein PNG in ICO und Apple Touch Icons zu konvertieren. Dieses Tool macht alles mit einem Klick.\"",
    "David K.": "David K.",
    "Aug 2025": "Aug. 2025",
    "\"Clean interface, no ads, and it respects privacy. Highly recommended for UI designers and developers.\"": "\"Saubere Benutzeroberfläche, werbefrei und datenschutzfreundlich. Sehr zu empfehlen für UI-Designer und Entwickler.\"",
    "Elena R.": "Elena R.",
    "Agency Owner": "Agenturleiter",
    "Jul 2025": "Juli 2025",
    "\"We use this for all our client projects now. The outputs are always crisp, and the HTML code snippets save us so much time.\"": "\"Wir nutzen dies jetzt für alle unsere Kundenprojekte. Die Ergebnisse sind immer gestochen scharf, und die HTML-Code-Snippets sparen uns viel Zeit.\"",
    "Michael T.": "Michael T.",
    "Jun 2025": "Juni 2025",
    "\"Finally a favicon generator that understands modern web requirements. The dark mode theme of the site itself is gorgeous too!\"": "\"Endlich ein Favicon-Generator, der moderne Webanforderungen versteht. Das Dark-Mode-Design der Website selbst ist ebenfalls großartig!\"",
    "Jessica L.": "Jessica L.",
    "May 2025": "Mai 2025",
    "\"Super reliable tool. I love that it gives you exactly what you need without making you jump through hoops or sign up.\"": "\"Super zuverlässiges Tool. Ich liebe es, dass es einem genau das liefert, was man braucht, ohne Registrierungszwang oder lästige Schritte.\"",
    "Ryan P.": "Ryan P.",
    "Nov 2025": "Nov. 2025",
    "\"Absolutely flawless execution. The generated zip file is perfectly organized and the icons look great on all devices.\"": "\"Absolut makellose Ausführung. Die generierte ZIP-Datei ist perfekt organisiert und die Symbole sehen auf allen Geräten super aus.\"",
    "Amanda B.": "Amanda B.",
    "Marketing Director": "Marketingleiterin",
    "\"It took me less than a minute to update our company website favicons. The process is incredibly intuitive.\"": "\"Es hat weniger als eine Minute gedauert, die Favicons unserer Firmenwebsite zu aktualisieren. Der Prozess ist unglaublich intuitiv.\"",
    "Chris W.": "Chris W.",
    "Startup Founder": "Startup-Gründer",
    "\"One less thing to worry about when launching a new product. Just drag, drop, and you have perfect favicons.\"": "\"Eine Sorge weniger beim Launch eines neuen Produkts. Einfach Drag-and-Drop, und schon hat man perfekte Favicons.\"",
    "Nina S.": "Nina S.",
    "Freelance Web Designer": "Freie Webdesignerin",
    "\"I recommend this tool to all my peers. It handles transparency perfectly and the ICO files are always valid.\"": "\"Ich empfehle dieses Tool allen meinen Kollegen. Es verarbeitet Transparenz perfekt und die ICO-Dateien sind immer valide.\"",
    "Tom H.": "Tom H.",
    "CTO": "CTO",
    "\"Simple, effective, and does exactly what it says on the tin. No bloated features, just a solid utility.\"": "\"Einfach, effektiv und tut genau das, was es verspricht. Keine überflüssigen Features, einfach ein solides Tool.\"",
    "Laura C.": "Laura C.",
    "Blogger": "Bloggerin",
    "\"I am not very technical, but this tool made it so easy to get a professional icon for my blog. Thank you!\"": "\"Ich bin technisch nicht sehr versiert, aber dieses Tool hat es mir so einfach gemacht, ein professionelles Icon für meinen Blog zu erstellen. Danke!\"",
    "Frontend Developer": "Frontend-Entwickler",
    "Web Designer": "Webdesigner",
    "Software Engineer": "Softwareentwickler",
    "UI/UX Designer": "UI/UX-Designer",
    "Full Stack Dev": "Full-Stack-Entwickler",
    "Product Manager": "Produktmanager",
    "Indie Hacker": "Indie-Hacker",
    "Tech Lead": "Technischer Leiter",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Generiert gestochen scharfe 16x16-Symbole ohne Unschärfe. Der von ihnen verwendete Skalierungsalgorithmus ist definitiv von hoher Qualität.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Als UX-Designer schätze ich Tools, die einfach funktionieren. Die Drag-and-Drop-Zone ist riesig und reaktionsschnell.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funktioniert einwandfrei auf meinem Mac. Die generierte Zip-Datei ist perfekt strukturiert. Sehr zu empfehlen.",

    // FAQs
    "Frequently Asked Questions": "Häufig gestellte Fragen (FAQ)",
    "Find answers to common questions about our favicon conversion service": "Hier finden Sie Antworten auf häufige Fragen zu unserem Favicon-Konvertierungsservice",
    "Getting Started": "Erste Schritte",
    "Features": "Funktionen",
    "Technology": "Technologie",
    "About Us": "Über uns",
    "What is a favicon?": "Was ist ein Favicon?",
    "A favicon (short for 'favorite icon') is a small icon that represents your website in browser tabs, bookmarks, history logs, and address bars. It helps users identify your brand visually.": "Ein Favicon (kurz für 'favorite icon') ist ein kleines Symbol, das Ihre Website in Browser-Tabs, Lesezeichen, dem Verlauf und Adresszeilen repräsentiert. Es hilft Benutzern, Ihre Marke visuell wiederzuerkennen.",
    "How can I convert a PNG to a favicon online?": "Wie kann ich ein PNG online in ein Favicon konvertieren?",
    "Simply drag and drop your PNG image into the upload box at the top, customize your background color, padding, or corners, and download the compiled zip package instantly.": "Ziehen Sie einfach Ihr PNG-Bild per Drag-and-Drop in das obige Upload-Feld, passen Sie Hintergrundfarbe, Abstände oder Ecken an und laden Sie das fertige ZIP-Paket sofort herunter.",
    "Do I need to install any software?": "Muss ich eine Software installieren?",
    "No, our favicon converter runs 100% in your web browser. No plugins, extensions, or software installations are needed.": "Nein, unser Favicon-Konverter läuft zu 100 % in Ihrem Webbrowser. Es sind keine Plugins, Erweiterungen oder Softwareinstallationen erforderlich.",
    "Do I need to create an account?": "Muss ich ein Benutzerkonto erstellen?",
    "No, the tool is completely free, open, and anonymous. There is no email signup, registration, or subscription required.": "Nein, das Tool ist völlig kostenlos, offen und anonym. Es ist keine E-Mail-Registrierung, Anmeldung oder ein Abonnement erforderlich.",
    "What file formats does the tool generate?": "Welche Dateiformate generiert das Tool?",
    "It outputs a multi-size favicon.ico (16px, 32px, 48px), high-res PNG browser icons, Apple Touch Icons (180x180), Android Chrome icons (192x192, 512x512), and site.webmanifest.": "Es generiert ein Multi-Size-favicon.ico (16px, 32px, 48px), hochauflösende PNG-Browser-Icons, Apple Touch Icons (180x180), Android Chrome Icons (192x192, 512x512) und eine site.webmanifest-Datei.",
    "Does the tool support transparent PNGs?": "Unterstützt das Tool transparente PNGs?",
    "Yes! It preserves transparency by default. You can also turn off transparency and fill the background with any color of your choice.": "Ja! Die Transparenz bleibt standardmäßig erhalten. Sie können die Transparenz auch deaktivieren und den Hintergrund mit einer beliebigen Farbe Ihrer Wahl füllen.",
    "Can I choose specific output sizes?": "Kann ich bestimmte Ausgabegrößen wählen?",
    "Yes, our Options Panel allows you to select or deselect specific sizes so you only download the icons you need.": "Ja, in unseren Einstellungen können Sie bestimmte Größen aktivieren oder deaktivieren, sodass Sie nur die Icons herunterladen, die Sie wirklich benötigen.",
    "What is a site.webmanifest file?": "Was ist eine site.webmanifest-Datei?",
    "It is a JSON configuration file containing app name metadata and icon routes that modern Android devices and Progressive Web Apps (PWA) require to install your site to the home screen.": "Es handelt sich um eine JSON-Konfigurationsdatei, die App-Namens-Metadaten und Symbolpfade enthält. Moderne Android-Geräte und Progressive Web Apps (PWA) benötigen diese, um Ihre Website auf dem Startbildschirm zu installieren.",
    "How does client-side favicon conversion work?": "Wie funktioniert die clientseitige Favicon-Konvertierung?",
    "We use HTML5 Canvas to scale and draw images, and compile the favicon.ico binary file using byte-level ArrayBuffers directly in your browser's memory.": "Wir verwenden HTML5 Canvas zum Skalieren und Zeichnen von Bildern und erstellen die binäre favicon.ico-Datei mithilfe von ArrayBuffers auf Byte-Ebene direkt im Arbeitsspeicher Ihres Browsers.",
    "Does the converter support large images?": "Unterstützt der Konverter große Bilder?",
    "Yes, it comfortably handles high-resolution images up to 5MB, resizing them using bilinear filtering to preserve crisp contours.": "Ja, er verarbeitet problemlos hochauflösende Bilder bis zu 5 MB und skaliert sie mithilfe bilinearer Filterung, um scharfe Konturen zu erhalten.",
    "Why is the favicon.ico file important?": "Warum ist die Datei favicon.ico wichtig?",
    "Although modern browsers support PNG favicons, the legacy favicon.ico format is still required as a fallback for older versions of Internet Explorer and certain desktop shortcut managers.": "Obwohl moderne Browser PNG-Favicons unterstützen, ist das alte favicon.ico-Format weiterhin als Fallback für ältere Internet Explorer-Versionen und bestimmte Desktop-Verknüpfungs-Manager erforderlich.",
    "How fast is the conversion process?": "Wie schnell ist der Konvertierungsprozess?",
    "The conversion is nearly instantaneous (under 50 milliseconds) since it processes everything locally on your computer instead of uploading to a remote server.": "Die Konvertierung erfolgt nahezu verzögerungsfrei (unter 50 Millisekunden), da alles lokal auf Ihrem Computer verarbeitet wird, anstatt es auf einen Remote-Server hochzuladen.",
    "Is my image secure and private?": "Ist mein Bild sicher und privat?",
    "Yes, absolutely. Your images never leave your browser because processing runs locally. We do not transmit, analyze, or store any of your files.": "Ja, absolut. Ihre Bilder verlassen Ihren Browser nie, da die Verarbeitung lokal erfolgt. Wir übertragen, analysieren oder speichern Ihre Dateien nicht.",
    "Why should I choose PNGtoFavicon.com?": "Warum sollte ich mich für PNGtoFavicon.com entscheiden?",
    "We offer a developer-friendly, privacy-first, fully automated tool that outputs complete, standards-compliant icon packages for all modern devices, entirely free of charge.": "Wir bieten ein entwicklerfreundliches, datenschutzorientiertes und vollautomatisches Tool, das komplette, standardkonforme Icon-Pakete für alle modernen Geräte ausgibt — absolut kostenlos.",
    "Can I use this tool on mobile devices?": "Kann ich dieses Tool auf mobilen Geräten verwenden?",
    "Yes! The website and conversion engine are fully responsive, so you can build and download your favicons on any mobile phone or tablet.": "Ja! Die Website und die Konvertierungs-Engine sind vollständig responsiv, sodass Sie Ihre Favicons auf jedem Smartphone oder Tablet erstellen und herunterladen können.",
    "Is this converter completely free?": "Ist dieser Konverter wirklich kostenlos?",
    "Yes, 100% free with no limits, no watermark overlays, and no hidden subscription tiers.": "Ja, 100 % kostenlos, ohne Einschränkungen, ohne Wasserzeichen und ohne versteckte kostenpflichtige Abos.",

    // Call to Action
    "Start Converting PNG to Favicon for Free Today": "Starten Sie noch heute mit der kostenlosen Konvertierung von PNG in Favicon",
    "Join 50,000+ users who trust PNGtoFavicon.com for accurate, fast, and completely free favicon generation.": "Schließen Sie sich über 50.000 Nutzern an, die PNGtoFavicon.com für die präzise, schnelle und völlig kostenlose Favicon-Erstellung vertrauen.",
    "Start Converting Now - It's Free!": "Jetzt konvertieren — es ist kostenlos!",

    // Explore Tools
    "Explore More Favicon Tools": "Entdecken Sie weitere Favicon-Tools",
    "PNGtoFavicon offers a complete suite of tools for all your favicon needs": "PNGtoFavicon bietet ein umfassendes Set an Tools für alle Ihre Favicon-Anforderungen",
    "Create a favicon from letters, initials, or any text. Choose fonts, colors, and styles to generate a unique text-based favicon for your brand.": "Erstellen Sie ein Favicon aus Buchstaben, Initialen oder beliebigem Text. Wählen Sie Schriftarten, Farben und Stile aus, um ein einzigartiges textbasiertes Favicon für Ihre Marke zu generieren.",
    "Try it free →": "Kostenlos testen →",
    "Choose from hundreds of emojis to instantly create a colorful, expressive favicon. Perfect for personal projects, blogs, and quick prototypes.": "Wählen Sie aus Hunderten von Emojis, um sofort ein farbenfrohes, ausdrucksstarkes Favicon zu erstellen. Perfekt für persönliche Projekte, Blogs und schnelle Prototypen.",
    "Validate your website's favicon setup. Enter any URL to check for missing sizes, incorrect formats, and cross-platform compatibility issues.": "Überprüfen Sie das Favicon-Setup Ihrer Website. Geben Sie eine beliebige URL ein, um auf fehlende Größen, falsche Formate und Kompatibilitätsprobleme zu testen.",
    "Check now →": "Jetzt prüfen →",

    // Footer
    "Convert PNG to Favicon instantly — free online tool": "PNG in Favicon sofort konvertieren — kostenloses Online-Tool",
    "Tools": "Tools",
    "PNG to Favicon Converter": "PNG-in-Favicon-Konverter",
    "Resources": "Ressourcen",
    "Favicon Sizes Guide": "Leitfaden für Favicon-Größen",
    "What is a Favicon?": "Was ist ein Favicon?",
    "Company": "Unternehmen",
    "About": "Über uns",
    "Contact": "Kontakt",
    "Privacy Policy": "Datenschutzerklärung",
    "Terms of Service": "Nutzungsbedingungen",
    "Cookie Policy": "Cookie-Richtlinie",
    "© 2026 PNGtoFavicon.com — All rights reserved.": "© 2026 PNGtoFavicon.com — Alle Rechte vorbehalten.",

    // E-E-A-T Contacts
    "Direct Contact": "Direkter Kontakt",
    "Support Channels": "Support-Kanäle",
    "Chat on WhatsApp": "Auf WhatsApp chatten",
    "Contact Support:": "Support kontaktieren:",
    "bishaloli610@gmail.com": "bishaloli610@gmail.com",
    "+977 9866735560": "+977 9866735560",

    // Additional missing parts
    "Generate favicons for all platforms instantly from your PNG logo. 100% free, private, and client-side.": "Erstellen Sie sofort Favicons für alle Plattformen aus Ihrem PNG-Logo. 100% kostenlos, privat und clientseitig.",
    "Select Background Color": "Hintergrundfarbe wählen",
    "Select Padding": "Polsterung (Padding) wählen",
    "Select Corner Radius": "Eckenradius wählen",
    "Upload a PNG image to generate a zip file with all standard favicon sizes.": "Laden Sie ein PNG-Bild hoch, um eine ZIP-Datei mit allen Standard-Favicon-Größen zu generieren.",
    "File Details": "Dateidetails",
    "Dimensions": "Dimensionen",
    "File Size": "Dateigröße",
    "HTML Code Snippet to Include in Head": "HTML-Code-Snippet für den Head-Bereich",
    "Copy code to clipboard": "Code in die Zwischenablage kopieren",
    "Copied!": "Kopiert!",
    "Customize Options": "Optionen anpassen",
    "Generate Manifest": "Manifest generieren",
    "Manifest.json details": "Manifest.json Details",
    "App Short Name": "Kurzname der App",
    "Theme Color": "Designfarbe (Theme Color)",
    "Background Color": "Hintergrundfarbe (Background Color)",
    "Generating your favicon files...": "Ihre Favicon-Dateien werden generiert...",
    "Done! Download your favicon pack below.": "Fertig! Laden Sie Ihr Favicon-Paket unten herunter.",
    "Once you drag & drop or browse your PNG image, the browser utilizes the HTML5 FileReader API to read your file locally, converting it to a secure in-memory data stream without uploading a single byte to external servers.": "Sobald Sie Ihr PNG-Bild per Drag-and-Drop hineinziehen oder auswählen, nutzt der Browser die HTML5-FileReader-API, um Ihre Datei lokal zu lesen und in einen sicheren In-Memory-Datenstrom umzuwandeln — ohne ein einziges Byte auf externe Server hochzuladen.",
    "Select Sizes to Include": "Einzuschließende Größen wählen",

    // JSON-LD Schema FAQ Page
    "What is a favicon?": "Was ist ein Favicon?",
    "A favicon (short for \"favorite icon\") is a small icon associated with a website. It appears in browser tabs, bookmark lists, browser history, and search results. Favicons help users quickly identify your website among multiple open tabs and bookmarks. Most modern browsers support multiple favicon sizes for different contexts — from tiny 16×16 pixel tab icons to large 512×512 pixel icons used by Progressive Web Apps (PWAs) for home screen shortcuts and splash screens.": "Ein Favicon (kurz für „Favorite Icon“) ist ein kleines Symbol, das mit einer Website verknüpft ist. Es erscheint in Browser-Tabs, Lesezeichenlisten, dem Browserverlauf und Suchergebnissen. Favicons helfen Nutzern, Ihre Website zwischen mehreren geöffneten Tabs und Lesezeichen schnell zu identifizieren. Die meisten modernen Browser unterstützen mehrere Favicon-Größen für verschiedene Kontexte — von winzigen 16×16-Pixel-Tab-Symbolen bis hin zu großen 512×512-Pixel-Symbolen, die von Progressive Web Apps (PWAs) für Startbildschirm-Verknüpfungen und Splash-Screens verwendet werden.",
    "What sizes do I need for a favicon?": "Welche Favicon-Größen benötige ich?",
    "For comprehensive cross-browser and cross-device support, you need: 16×16 (standard tab icon), 32×32 (HiDPI tab icon), 48×48 (Windows site icon), 180×180 (Apple Touch Icon), 192×192 (Android Chrome icon), and 512×512 (PWA install icon). PNGtoFavicon generates all of these automatically from a single PNG upload, plus a multi-size favicon.ico file.": "Für eine umfassende Unterstützung aller Browser und Geräte benötigen Sie: 16×16 (Standard-Tab-Icon), 32×32 (HiDPI-Tab-Icon), 48×48 (Windows-Website-Icon), 180×180 (Apple-Touch-Icon), 192×192 (Android-Chrome-Icon) und 512×512 (PWA-Installations-Icon). PNGtoFavicon generiert alle diese Größen automatisch aus einem einzigen PNG-Upload, plus einer Multi-Size-favicon.ico-Datei.",
    "How do I add a favicon to my website?": "Wie füge ich ein Favicon zu meiner Website hinzu?",
    "After downloading your favicon package from PNGtoFavicon, extract the ZIP file to your website's root directory and add the provided HTML link tags inside your <head> section. PNGtoFavicon generates the exact HTML code snippet you need, ready to copy and paste.": "Nachdem Sie Ihr Favicon-Paket von PNGtoFavicon heruntergeladen haben, entpacken Sie die ZIP-Datei in das Stammverzeichnis Ihrer Website und fügen Sie die bereitgestellten HTML-Link-Tags in Ihren <head>-Bereich ein. PNGtoFavicon generiert das exakte HTML-Code-Snippet, das Sie kopieren und einfügen können.",
    "Is my image uploaded to a server?": "Wird mein Bild auf einen Server hochgeladen?",
    "No — your image never leaves your browser. PNGtoFavicon processes everything 100% client-side using JavaScript and the HTML5 Canvas API. No data is sent to any server, making this the most private favicon generator available.": "Nein — Ihr Bild verlässt niemals Ihren Browser. PNGtoFavicon verarbeitet alles zu 100 % clientseitig über JavaScript und die HTML5 Canvas API. Es werden keine Daten an einen Server gesendet, was dies zum sichersten und privatsphäre-freundlichsten Favicon-Generator macht.",
    "What file formats are supported for input?": "Welche Dateiformate werden für den Input unterstützt?",
    "PNGtoFavicon accepts PNG (recommended, supports transparency), JPG/JPEG, SVG (vector format), WEBP (modern format), and GIF. For best results, use a square PNG image of at least 512×512 pixels with a transparent background.": "PNGtoFavicon akzeptiert PNG (empfohlen, da es Transparenz unterstützt), JPG/JPEG, SVG (Vektorformat), WEBP (modernes Format) und GIF. Für beste Ergebnisse verwenden Sie ein quadratisches PNG-Bild von mindestens 512×512 Pixeln mit transparentem Hintergrund.",
    "Can I use this tool on mobile?": "Kann ich dieses Tool auf dem Smartphone nutzen?",
    "Yes! PNGtoFavicon is fully responsive and works on any device with a modern web browser — including smartphones and tablets. You can upload images, configure options, and download your complete favicon package right from your mobile device.": "Ja! PNGtoFavicon ist vollständig responsiv und funktioniert auf jedem Gerät mit einem modernen Webbrowser — einschließlich Smartphones und Tablets. Sie können Bilder hochladen, Optionen konfigurieren und Ihr komplettes Favicon-Paket direkt von Ihrem Mobilgerät herunterladen.",
    "What is the difference between .ico and .png favicons?": "Was ist der Unterschied zwischen .ico- und .png-Favicons?",
    "The .ico format is a legacy container that can hold multiple icon sizes in a single file, required for compatibility with older browsers. Modern browsers prefer individual .png files specified with link tags, offering better quality and smaller file sizes. PNGtoFavicon generates both formats.": "Das .ico-Format ist ein veraltetes Container-Format, das mehrere Icon-Größen in einer einzigen Datei enthalten kann und für die Kompatibilität mit älteren Browsern erforderlich ist. Moderne Browser bevorzugen einzelne .png-Dateien, die über Link-Tags angegeben werden, da sie bessere Qualität und kleinere Dateigrößen bieten. PNGtoFavicon generiert beide Formate.",
    "What is site.webmanifest and do I need it?": "Was ist die site.webmanifest-Datei und benötige ich sie?",
    "The site.webmanifest is a JSON file that tells browsers about your web application — including its name, theme color, and icon references. It's essential for Progressive Web App (PWA) functionality and improves compatibility with Android Chrome and other modern browsers.": "Die site.webmanifest ist eine JSON-Datei, die Browsern Details über Ihre Web-App mitteilt — einschließlich ihres Namens, der Theme-Farbe und der Icon-Referenzen. Sie ist für die Funktionalität von Progressive Web Apps (PWAs) unverzichtbar und verbessert die Kompatibilität mit Android Chrome und anderen modernen Browsern.",

    // Missing translations
    "PNG to Favicon": "PNG in Favicon",
    "Convert any PNG image to a complete favicon package instantly. Free, fast, and 100% client-side — your files never leave your browser.": "Konvertieren Sie jedes PNG-Bild sofort in ein vollständiges Favicon-Paket. Kostenlos, schnell und zu 100 % clientseitig — Ihre Dateien verlassen niemals Ihren Browser.",
    "or": "oder",
    "browse files": "Dateien durchsuchen",
    "🔒 100% Private": "🔒 100% Privat",
    "⚡ Instant Convert": "⚡ Sofortige Konvertierung",
    "📦 All Sizes Included": "📦 Alle Größen enthalten",
    "💰 Completely Free": "💰 Völlig kostenlos",
    "⚙️ Options": "⚙️ Optionen",
    "Keep transparent": "Transparenz beibehalten",
    "Round corners": "Abgerundete Ecken",
    "Include site.webmanifest": "site.webmanifest einschließen",
    "📦 Preview": "📦 Vorschau",
    "Download All (ZIP)": "Alle herunterladen (ZIP)",
    "🔗 HTML Code": "🔗 HTML-Code",
    "Add this to your website's": "Fügen Sie dies in den",
    "tag:": "Ihrer Website ein:",
    "Why Choose PNGtoFavicon.com for Favicon Generation?": "Warum PNGtoFavicon.com für die Favicon-Erstellung wählen?",
    "The most powerful free online favicon builder that converts images into standards-compliant browser assets with professional accuracy and lightning speed.": "Der leistungsstärkste kostenlose Online-Favicon-Builder, der Bilder mit professioneller Präzision und in Blitzschnelle in standardkonforme Browser-Assets konvertiert.",
    "Instant Client-Side Engine": "Sofortige clientseitige Engine",
    "Pixel-Perfect Rescaling": "Pixelgenaue Skalierung",
    "High-fidelity downsampling that keeps edges crisp and details readable at 16×16px sizes.": "Hochwertiges Downsampling, das Kanten scharf und Details auch bei einer Größe von 16×16 Pixeln lesbar hält.",
    "All Image Formats Supported": "Alle Bildformate unterstützt",
    "Works with PNG, JPG, SVG, WEBP, GIF, and other popular image formats with ease.": "Funktioniert problemlos mit PNG, JPG, SVG, WEBP, GIF und anderen gängigen Bildformaten.",
    "Universal Device Support": "Universeller Gerätesupport",
    "Generates legacy ICO, Apple Touch Icons, Android Chrome sizes, and PWAs inside one ZIP package.": "Generiert veraltete ICO-Formate, Apple Touch Icons, Android Chrome-Größen und PWAs in einem einzigen ZIP-Paket.",
    "100% Secure & Private": "100% sicher & privat",
    "Completely Free & Open": "Völlig kostenlos & offen",
    "No email registrations, no subscriptions, no paywalls. Completely free developer tools.": "Keine E-Mail-Registrierung, keine Abonnements, keine Paywalls. Völlig kostenlose Entwickler-Tools.",
    "Powerful features at your fingertips": "Leistungsstarke Funktionen direkt in Ihrer Hand",
    "How Our PNG to Favicon Converter Works": "Wie unser PNG-in-Favicon-Konverter funktioniert",
    "Discover the advanced browser-based technology we use to generate your favicons securely": "Entdecken Sie die fortschrittliche browserbasierte Technologie, die wir für die sichere Erstellung Ihrer Favicons nutzen",
    "Local File Reading": "Lokales Einlesen der Datei",
    "Offscreen Downscaling": "Offscreen-Downscaling",
    "To generate all necessary resolutions, the tool spins up hidden, offscreen HTML5 Canvas elements. It applies bilinear interpolation filters to scale down your logo while maintaining crisp, sharp contours.": "Um alle erforderlichen Auflösungen zu generieren, erstellt das Tool im Hintergrund unsichtbare HTML5-Canvas-Elemente. Es wendet bilineare Interpolationsfilter an, um Ihr Logo zu verkleinern und gleichzeitig scharfe Konturen beizubehalten.",
    "Options Processing": "Optionen-Verarbeitung",
    "If you customize settings, the canvas modifies the rendering stack. Toggling off transparency paints a solid background layer, and rounded corners apply a circular clipping mask over the bounding box.": "Wenn Sie Einstellungen anpassen, ändert das Canvas den Rendering-Stack. Das Deaktivieren der Transparenz zeichnet eine solide Hintergrundebene, und abgerundete Ecken wenden eine kreisförmige Maske auf das Begrenzungsfeld an.",
    "Binary ICO Compilation": "Binäre ICO-Kompilierung",
    "ZIP Compressing & Download": "ZIP-Komprimierung & Download",
    "The files and site.webmanifest schema are loaded into a virtual folder using JSZip. The browser builds the package locally, registers a temporary URL reference, and triggers a prompt to save the ZIP.": "Die Dateien und das Schema der site.webmanifest werden mit JSZip in einen virtuellen Ordner geladen. Der Browser erstellt das Paket lokal, registriert eine temporäre URL-Referenz und fordert Sie zum Speichern der ZIP-Datei auf.",
    "Perfect for Every Use Case": "Perfekt für jeden Anwendungsfall",
    "Discover how our PNG to Favicon tool works across different scenarios": "Erfahren Sie, wie unser PNG-in-Favicon-Tool in verschiedenen Szenarien funktioniert",
    "Web Developers": "Webentwickler",
    "Instantly generate all required favicon sizes for your web projects from a single PNG file.": "Generieren Sie aus einer einzigen PNG-Datei sofort alle erforderlichen Favicon-Größen für Ihre Webprojekte.",
    "Language": "Sprache"
  },
  es: {
    "Free": "Gratis",
    "Converter": "Convertidor",
    "Text to Favicon": "Texto a Favicon",
    "Emoji to Favicon": "Emoji a Favicon",
    "Favicon Checker": "Comprobador de Favicon",
    "Tutorials": "Tutoriales",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Soporta: PNG, JPG, SVG, WEBP, GIF (máx. 5MB)",
    "Output Sizes": "Tamaños de Salida",
    "Background Color (for transparent PNGs)": "Color de Fondo (para PNGs transparentes)",
    "Copy": "Copiar",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Archivo de manifiesto de aplicación web que contiene referencias de iconos, color de tema y color de fondo. Esencial para el soporte PWA y la integración en la pantalla de inicio de Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon frente a otras herramientas del mercado",
    "See how we compare to other favicon generators on the market": "Vea cómo nos comparamos con otros generadores de favicon del mercado",
    "Feature": "Característica",
    "Other Tools": "Otras Herramientas",
    "Price": "Precio",
    "Free forever": "Gratis para siempre",
    "Freemium / Paid tiers": "Freemium / Niveles de pago",
    "Privacy": "Privacidad",
    "100% Client-side": "100% Lado del cliente",
    "Files uploaded to servers": "Archivos subidos a servidores",
    "Speed": "Velocidad",
    "Instant processing": "Procesamiento instantáneo",
    "Depends on server load": "Depende de la carga del servidor",
    "File Formats": "Formatos de Archivo",
    "ICO + PNG + Manifest": "ICO + PNG + Manifiesto",
    "Often ICO only": "A menudo solo ICO",
    "No Registration": "Sin Registro",
    "No signup needed": "No se requiere registro",
    "Sometimes required": "A veces requerido",
    "Multi-platform": "Multiplataforma",
    "All devices & browsers": "Todos los dispositivos y navegadores",
    "Limited platform support": "Soporte de plataforma limitado",
    "Testimonials": "Testimonios",
    "What Our Users Say": "Lo que dicen nuestros usuarios",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Más de 50.000 desarrolladores, diseñadores y creadores confían en PNGtoFavicon para sus proyectos.",
    "from 500+ reviews": "de más de 500 reseñas",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "La forma más rápida de generar todos los tamaños de favicon. Literalmente toma 2 segundos y maneja perfectamente los nuevos formatos manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Solía ​​usar ImageMagick para esto, pero este sitio es mucho más simple. Arrastrar, soltar, descargar, listo.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Me encanta que se ejecute completamente en el navegador. No tengo que preocuparme por subir logotipos confidenciales de clientes a algún servidor aleatorio.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Perfecto para convertir PNG de alta resolución al formato ICO heredado. Una herramienta imprescindible para mi flujo de trabajo de desarrollo web diario.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interfaz de usuario limpia, procesamiento rápido y le brinda las etiquetas HTML exactas para copiar y pegar. ¡Excelente herramienta!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "El manejo de la transparencia es perfecto. Otros convertidores generalmente estropean los canales alfa, pero este funciona perfectamente.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Finalmente, un generador de favicons que incluye el ícono PWA de 512x512. Me ahorra la necesidad de cambiar el tamaño de las imágenes manualmente.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Sencillo y eficaz. La interfaz en modo oscuro es un buen detalle para nosotros, los desarrolladores que trabajamos hasta altas horas de la noche.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "He marcado esto como favorito. Es la única herramienta de favicon que he encontrado que no te bombardea con anuncios o ventanas emergentes.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Genera iconos nítidos de 16x16 sin desenfoque. El algoritmo de cambio de tamaño que utilizan es definitivamente de alta calidad.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Como diseñador de UX, aprecio las herramientas que simplemente funcionan. La zona de arrastrar y soltar es enorme y receptiva.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funciona impecablemente en mi Mac. El archivo zip generado está perfectamente estructurado. Muy recomendable.",
    "Frontend Developer": "Desarrollador Frontend",
    "Web Designer": "Diseñador Web",
    "Software Engineer": "Ingeniero de Software",
    "UI/UX Designer": "Diseñador UI/UX",
    "Full Stack Dev": "Desarrollador Full Stack",
    "Product Manager": "Gerente de Producto",
    "Indie Hacker": "Desarrollador Independiente",
    "Tech Lead": "Líder Técnico"
  },
  fr: {
    "Free": "Gratuit",
    "Converter": "Convertisseur",
    "Text to Favicon": "Texte en Favicon",
    "Emoji to Favicon": "Emoji en Favicon",
    "Favicon Checker": "Vérificateur de Favicon",
    "Tutorials": "Tutoriels",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Prend en charge : PNG, JPG, SVG, WEBP, GIF (max 5 Mo)",
    "Output Sizes": "Tailles de Sortie",
    "Background Color (for transparent PNGs)": "Couleur de Fond (pour PNG transparents)",
    "Copy": "Copier",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Fichier manifeste d'application Web contenant des références d'icônes, la couleur du thème et la couleur d'arrière-plan. Essentiel pour la prise en charge des PWA et l'intégration à l'écran d'accueil Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon par rapport aux autres outils du marché",
    "See how we compare to other favicon generators on the market": "Voyez comment nous nous comparons aux autres générateurs de favicon du marché",
    "Feature": "Fonctionnalité",
    "Other Tools": "Autres Outils",
    "Price": "Prix",
    "Free forever": "Gratuit pour toujours",
    "Freemium / Paid tiers": "Freemium / Niveaux payants",
    "Privacy": "Confidentialité",
    "100% Client-side": "100% Côté client",
    "Files uploaded to servers": "Fichiers téléchargés sur des serveurs",
    "Speed": "Vitesse",
    "Instant processing": "Traitement instantané",
    "Depends on server load": "Dépend de la charge du serveur",
    "File Formats": "Formats de Fichiers",
    "ICO + PNG + Manifest": "ICO + PNG + Manifeste",
    "Often ICO only": "Souvent ICO uniquement",
    "No Registration": "Pas d'Inscription",
    "No signup needed": "Aucune inscription nécessaire",
    "Sometimes required": "Parfois requis",
    "Multi-platform": "Multi-plateforme",
    "All devices & browsers": "Tous les appareils et navigateurs",
    "Limited platform support": "Prise en charge limitée des plateformes",
    "Testimonials": "Témoignages",
    "What Our Users Say": "Ce que disent nos utilisateurs",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Plus de 50 000 développeurs, designers et créateurs font confiance à PNGtoFavicon pour leurs projets.",
    "from 500+ reviews": "à partir de plus de 500 avis",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Le moyen le plus rapide de générer toutes les tailles de favicon. Cela prend littéralement 2 secondes et gère parfaitement les nouveaux formats manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "J'utilisais ImageMagick pour cela, mais ce site est tellement plus simple. Glisser, déposer, télécharger, terminé.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "J'adore qu'il s'exécute complètement dans le navigateur. Je n'ai pas à m'inquiéter de télécharger des logos clients sensibles sur un serveur aléatoire.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Parfait pour convertir des PNG haute résolution à l'ancien format ICO. Un outil indispensable pour mon flux de travail de développement Web quotidien.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interface utilisateur épurée, traitement rapide et vous donne les balises HTML exactes à copier-coller. Excellent outil !",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "La gestion de la transparence est parfaite. D'autres convertisseurs gâchent généralement les canaux alpha, mais celui-ci fonctionne parfaitement.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Enfin un générateur de favicon qui inclut l'icône PWA 512x512. M'évite de redimensionner manuellement les images.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Simple et efficace. L'interface en mode sombre est une touche agréable pour nous, développeurs travaillant tard le soir.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "J'ai mis cela dans mes favoris. C'est le seul outil de favicon que j'ai trouvé qui ne vous bombarde pas de publicités ou de popups.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Génère des icônes 16x16 nettes sans flou. L'algorithme de redimensionnement qu'ils utilisent est de très haute qualité.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "En tant que designer UX, j'apprécie les outils qui fonctionnent tout simplement. La zone de glisser-déposer est immense et réactive.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Fonctionne parfaitement sur mon Mac. Le fichier zip généré est parfaitement structuré. Hautement recommandé.",
    "Frontend Developer": "Développeur Frontend",
    "Web Designer": "Web Designer",
    "Software Engineer": "Ingénieur Logiciel",
    "UI/UX Designer": "Designer UI/UX",
    "Full Stack Dev": "Développeur Full Stack",
    "Product Manager": "Chef de Produit",
    "Indie Hacker": "Développeur Indépendant",
    "Tech Lead": "Responsable Technique"
  },
  id: {
    "Free": "Gratis",
    "Converter": "Konverter",
    "Text to Favicon": "Teks ke Favicon",
    "Emoji to Favicon": "Emoji ke Favicon",
    "Favicon Checker": "Pemeriksa Favicon",
    "Tutorials": "Tutorial",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Mendukung: PNG, JPG, SVG, WEBP, GIF (maks 5MB)",
    "Output Sizes": "Ukuran Output",
    "Background Color (for transparent PNGs)": "Warna Latar Belakang (untuk PNG transparan)",
    "Copy": "Salin",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "File Web App Manifest yang berisi referensi ikon, warna tema, dan warna latar belakang. Sangat penting untuk dukungan PWA dan integrasi layar beranda Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon vs Alat Lain di Pasaran",
    "See how we compare to other favicon generators on the market": "Lihat bagaimana kami dibandingkan dengan pembuat favicon lain di pasaran",
    "Feature": "Fitur",
    "Other Tools": "Alat Lainnya",
    "Price": "Harga",
    "Free forever": "Gratis selamanya",
    "Freemium / Paid tiers": "Freemium / Berbayar",
    "Privacy": "Privasi",
    "100% Client-side": "100% Sisi klien",
    "Files uploaded to servers": "File diunggah ke server",
    "Speed": "Kecepatan",
    "Instant processing": "Pemrosesan instan",
    "Depends on server load": "Tergantung pada beban server",
    "File Formats": "Format File",
    "ICO + PNG + Manifest": "ICO + PNG + Manifes",
    "Often ICO only": "Seringkali hanya ICO",
    "No Registration": "Tanpa Registrasi",
    "No signup needed": "Tidak perlu mendaftar",
    "Sometimes required": "Terkadang diperlukan",
    "Multi-platform": "Multi-platform",
    "All devices & browsers": "Semua perangkat & browser",
    "Limited platform support": "Dukungan platform terbatas",
    "Testimonials": "Testimoni",
    "What Our Users Say": "Apa Kata Pengguna Kami",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Lebih dari 50.000 pengembang, desainer, dan pembuat konten mempercayai PNGtoFavicon untuk proyek mereka.",
    "from 500+ reviews": "dari 500+ ulasan",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Cara tercepat untuk menghasilkan semua ukuran favicon. Secara harfiah membutuhkan waktu 2 detik dan menangani format manifest.json baru dengan sempurna.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Saya biasa menggunakan ImageMagick untuk ini, tetapi situs ini jauh lebih sederhana. Seret, lepas, unduh, selesai.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Suka karena berjalan sepenuhnya di browser. Saya tidak perlu khawatir mengunggah logo klien yang sensitif ke beberapa server acak.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Sempurna untuk mengonversi PNG resolusi tinggi ke format ICO lama. Alat yang harus dimiliki untuk alur kerja web dev harian saya.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "UI bersih, pemrosesan cepat, dan memberi Anda tag HTML persis untuk disalin-tempel. Alat luar biasa!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "Penanganan transparansi sangat tepat. Konverter lain biasanya mengacaukan saluran alpha, tetapi yang ini berfungsi dengan sempurna.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Akhirnya sebuah pembuat favicon yang menyertakan ikon PWA 512x512. Menyelamatkan saya dari mengubah ukuran gambar secara manual.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Sederhana dan efektif. Antarmuka mode gelap adalah sentuhan yang bagus untuk kami para pengembang yang bekerja hingga larut malam.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Saya telah menandai ini. Ini adalah satu-satunya alat favicon yang saya temukan yang tidak membombardir Anda dengan iklan atau popup.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Menghasilkan ikon 16x16 yang tajam tanpa keburaman. Algoritme pengubahan ukuran yang mereka gunakan pasti berkualitas tinggi.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Sebagai desainer UX, saya menghargai alat yang berfungsi begitu saja. Zona seret dan lepas sangat besar dan responsif.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Bekerja dengan sempurna di Mac saya. File zip yang dihasilkan terstruktur dengan sempurna. Sangat disarankan.",
    "Frontend Developer": "Pengembang Frontend",
    "Web Designer": "Desainer Web",
    "Software Engineer": "Insinyur Perangkat Lunak",
    "UI/UX Designer": "Desainer UI/UX",
    "Full Stack Dev": "Pengembang Full Stack",
    "Product Manager": "Manajer Produk",
    "Indie Hacker": "Peretas Indie",
    "Tech Lead": "Pemimpin Teknis"
  },
  pt: {
    "Free": "Gratuito",
    "Converter": "Conversor",
    "Text to Favicon": "Texto para Favicon",
    "Emoji to Favicon": "Emoji para Favicon",
    "Favicon Checker": "Verificador de Favicon",
    "Tutorials": "Tutoriais",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Suporta: PNG, JPG, SVG, WEBP, GIF (máx. 5MB)",
    "Output Sizes": "Tamanhos de Saída",
    "Background Color (for transparent PNGs)": "Cor de Fundo (para PNGs transparentes)",
    "Copy": "Copiar",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Arquivo de manifesto de aplicativo da Web contendo referências de ícones, cor de tema e cor de fundo. Essencial para suporte PWA e integração da tela inicial do Android.",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon vs Outras Ferramentas no Mercado",
    "See how we compare to other favicon generators on the market": "Veja como nos comparamos a outros geradores de favicon no mercado",
    "Feature": "Recurso",
    "Other Tools": "Outras Ferramentas",
    "Price": "Preço",
    "Free forever": "Grátis para sempre",
    "Freemium / Paid tiers": "Freemium / Planos pagos",
    "Privacy": "Privacidade",
    "100% Client-side": "100% Lado do cliente",
    "Files uploaded to servers": "Arquivos carregados em servidores",
    "Speed": "Velocidade",
    "Instant processing": "Processamento instantâneo",
    "Depends on server load": "Depende da carga do servidor",
    "File Formats": "Formatos de Arquivo",
    "ICO + PNG + Manifest": "ICO + PNG + Manifesto",
    "Often ICO only": "Frequentemente apenas ICO",
    "No Registration": "Sem Registro",
    "No signup needed": "Sem necessidade de inscrição",
    "Sometimes required": "Às vezes necessário",
    "Multi-platform": "Multiplataforma",
    "All devices & browsers": "Todos os dispositivos e navegadores",
    "Limited platform support": "Suporte limitado à plataforma",
    "Testimonials": "Depoimentos",
    "What Our Users Say": "O que nossos usuários dizem",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "Mais de 50.000 desenvolvedores, designers e criadores confiam no PNGtoFavicon para seus projetos.",
    "from 500+ reviews": "de mais de 500 avaliações",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "A maneira mais rápida de gerar todos os tamanhos de favicon. Literalmente leva 2 segundos e lida perfeitamente com os novos formatos manifest.json.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Eu costumava usar o ImageMagick para isso, mas este site é muito mais simples. Arraste, solte, baixe, pronto.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Adoro que ele rode completamente no navegador. Não preciso me preocupar em enviar logotipos confidenciais de clientes para algum servidor aleatório.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Perfeito para converter PNGs de alta resolução para o formato ICO legado. Uma ferramenta obrigatória para o meu fluxo de trabalho diário de desenvolvimento da web.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Interface de usuário limpa, processamento rápido e fornece as tags HTML exatas para copiar e colar. Excelente ferramenta!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "O manuseio da transparência é perfeito. Outros conversores costumam bagunçar os canais alfa, mas este funciona perfeitamente.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Finalmente um gerador de favicon que inclui o ícone PWA de 512x512. Me salva de redimensionar imagens manualmente.",
    "Simple and effective. The dark mode interface is a nice toque for us developers working late at night.": "Simples e eficaz. A interface do modo escuro é um toque agradável para nós, desenvolvedores que trabalhamos até tarde da noite.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Marquei isso nos favoritos. É a única ferramenta de favicon que encontrei que não o bombardeia com anúncios ou pop-ups.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Gera ícones nítidos de 16x16 sem desfoque. O algoritmo de redimensionamento que eles usam é definitivamente de alta qualidade.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Como designer de UX, aprecio ferramentas que simplesmente funcionam. A zona de arrastar e soltar é enorme e responsiva.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Funciona perfeitamente no meu Mac. O arquivo zip gerado é perfeitamente estruturado. Altamente recomendado.",
    "Frontend Developer": "Desenvolvedor Frontend",
    "Web Designer": "Web Designer",
    "Software Engineer": "Engenheiro de Software",
    "UI/UX Designer": "Designer de UI/UX",
    "Full Stack Dev": "Desenvolvedor Full Stack",
    "Product Manager": "Gerente de Produto",
    "Indie Hacker": "Indie Hacker",
    "Tech Lead": "Líder Técnico"
  },
  tr: {
    "Free": "Ücretsiz",
    "Converter": "Dönüştürücü",
    "Text to Favicon": "Metinden Favicon'a",
    "Emoji to Favicon": "Emoji'den Favicon'a",
    "Favicon Checker": "Favicon Denetleyici",
    "Tutorials": "Öğreticiler",
    "Blog": "Blog",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "Destekler: PNG, JPG, SVG, WEBP, GIF (maks 5MB)",
    "Output Sizes": "Çıktı Boyutları",
    "Background Color (for transparent PNGs)": "Arka Plan Rengi (şeffaf PNG'ler için)",
    "Copy": "Kopyala",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "Simge referanslarını, tema rengini ve arka plan rengini içeren Web Uygulaması Bildirim dosyası. PWA desteği ve Android ana ekran entegrasyonu için gereklidir.",
    "PNGtoFavicon vs Other Tools in The Market": "Piyasadaki Diğer Araçlara Karşı PNGtoFavicon",
    "See how we compare to other favicon generators on the market": "Piyasadaki diğer favicon oluşturucularla nasıl karşılaştırdığımızı görün",
    "Feature": "Özellik",
    "Other Tools": "Diğer Araçlar",
    "Price": "Fiyat",
    "Free forever": "Sonsuza kadar ücretsiz",
    "Freemium / Paid tiers": "Freemium / Ücretli katmanlar",
    "Privacy": "Gizlilik",
    "100% Client-side": "%100 İstemci tarafı",
    "Files uploaded to servers": "Sunuculara yüklenen dosyalar",
    "Speed": "Hız",
    "Instant processing": "Anında işleme",
    "Depends on server load": "Sunucu yüküne bağlıdır",
    "File Formats": "Dosya Biçimleri",
    "ICO + PNG + Manifest": "ICO + PNG + Bildirim",
    "Often ICO only": "Genellikle sadece ICO",
    "No Registration": "Kayıt Yok",
    "No signup needed": "Kayıt gerekmez",
    "Sometimes required": "Bazen gerekli",
    "Multi-platform": "Çoklu platform",
    "All devices & browsers": "Tüm cihazlar ve tarayıcılar",
    "Limited platform support": "Sınırlı platform desteği",
    "Testimonials": "Referanslar",
    "What Our Users Say": "Kullanıcılarımız Ne Diyor",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "50.000'den fazla geliştirici, tasarımcı ve yaratıcı projeleri için PNGtoFavicon'a güveniyor.",
    "from 500+ reviews": "500'den fazla incelemeden",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "Tüm favicon boyutlarını oluşturmanın en hızlı yolu. Kelimenin tam anlamıyla 2 saniye sürer ve yeni manifest.json formatlarını mükemmel şekilde işler.",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "Bunun için eskiden ImageMagick kullanıyordum ama bu site çok daha basit. Sürükle, bırak, indir, bitti.",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "Tamamen tarayıcıda çalışmasını seviyorum. Hassas müşteri logolarını rastgele bir sunucuya yükleme konusunda endişelenmeme gerek yok.",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "Yüksek çözünürlüklü PNG'leri eski ICO biçimine dönüştürmek için mükemmeldir. Günlük web geliştirme iş akışım için sahip olunması gereken bir araç.",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "Temiz kullanıcı arayüzü, hızlı işleme ve size kopyalayıp yapıştıracağınız tam HTML etiketlerini verir. Mükemmel bir araç!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "Şeffaflık işleme yerinde. Diğer dönüştürücüler genellikle alfa kanallarını bozar, ancak bu mükemmel çalışır.",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "Sonunda 512x512 PWA simgesini içeren bir favicon oluşturucu. Beni görüntüleri manuel olarak yeniden boyutlandırmaktan kurtarıyor.",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "Basit ve etkili. Karanlık mod arayüzü, gece geç saatlere kadar çalışan biz geliştiriciler için hoş bir dokunuş.",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "Bunu yer imlerine ekledim. Reklamlar veya açılır pencerelerle sizi bombardımana tutmayan bulduğum tek favicon aracı.",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "Bulanıklaştırmadan net 16x16 simgeler oluşturur. Kullandıkları yeniden boyutlandırma algoritması kesinlikle yüksek kalitededir.",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "Bir UX tasarımcısı olarak, sadece çalışan araçları takdir ediyorum. Sürükle ve bırak alanı devasa ve duyarlı.",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "Mac'imde kusursuz çalışıyor. Oluşturulan zip dosyası mükemmel şekilde yapılandırılmış. Şiddetle tavsiye edilir.",
    "Frontend Developer": "Frontend Geliştirici",
    "Web Designer": "Web Tasarımcı",
    "Software Engineer": "Yazılım Mühendisi",
    "UI/UX Designer": "UI/UX Tasarımcı",
    "Full Stack Dev": "Full Stack Geliştirici",
    "Product Manager": "Ürün Yöneticisi",
    "Indie Hacker": "Bağımsız Geliştirici",
    "Tech Lead": "Teknik Lider"
  },
  ur: {
    "Free": "مفت",
    "Converter": "کنورٹر",
    "Text to Favicon": "ٹیکسٹ سے فیویکن",
    "Emoji to Favicon": "ایموجی سے فیویکن",
    "Favicon Checker": "فیویکن چیکر",
    "Tutorials": "سبق",
    "Blog": "بلاگ",
    "Supports: PNG, JPG, SVG, WEBP, GIF (max 5MB)": "معاونت: PNG، JPG، SVG، WEBP، GIF (زیادہ سے زیادہ 5MB)",
    "Output Sizes": "آؤٹ پٹ سائز",
    "Background Color (for transparent PNGs)": "پس منظر کا رنگ (شفاف PNGs کے لیے)",
    "Copy": "کاپی",
    "Web App Manifest file containing icon references, theme color, and background color. Essential for PWA support and Android home screen integration.": "ویب ایپ مینی فیسٹ فائل جس میں آئیکن کے حوالہ جات، تھیم کا رنگ، اور پس منظر کا رنگ شامل ہے۔ PWA سپورٹ اور Android ہوم اسکرین کے انضمام کے لیے ضروری ہے۔",
    "PNGtoFavicon vs Other Tools in The Market": "PNGtoFavicon بمقابلہ مارکیٹ میں دیگر ٹولز",
    "See how we compare to other favicon generators on the market": "دیکھیں کہ ہم مارکیٹ میں موجود دیگر فیویکن جنریٹرز سے کیسے موازنہ کرتے ہیں۔",
    "Feature": "خصوصیت",
    "Other Tools": "دیگر ٹولز",
    "Price": "قیمت",
    "Free forever": "ہمیشہ کے لیے مفت",
    "Freemium / Paid tiers": "فریمیم / ادا شدہ درجات",
    "Privacy": "رازداری",
    "100% Client-side": "100% کلائنٹ سائیڈ",
    "Files uploaded to servers": "فائلیں سرورز پر اپ لوڈ کی گئیں۔",
    "Speed": "رفتار",
    "Instant processing": "فوری کارروائی",
    "Depends on server load": "سرور کے بوجھ پر منحصر ہے۔",
    "File Formats": "فائل فارمیٹس",
    "ICO + PNG + Manifest": "ICO + PNG + مینی فیسٹ",
    "Often ICO only": "اکثر صرف ICO",
    "No Registration": "کوئی رجسٹریشن نہیں۔",
    "No signup needed": "سائن اپ کی ضرورت نہیں۔",
    "Sometimes required": "بعض اوقات ضروری ہے۔",
    "Multi-platform": "ملٹی پلیٹ فارم",
    "All devices & browsers": "تمام آلات اور براؤزرز",
    "Limited platform support": "محدود پلیٹ فارم سپورٹ",
    "Testimonials": "تعریفیں",
    "What Our Users Say": "ہمارے صارفین کیا کہتے ہیں۔",
    "Over 50,000 developers, designers, and creators trust PNGtoFavicon for their projects.": "50,000 سے زیادہ ڈویلپرز، ڈیزائنرز، اور تخلیق کار اپنے پروجیکٹس کے لیے PNGtoFavicon پر بھروسہ کرتے ہیں۔",
    "from 500+ reviews": "500+ جائزوں سے",
    "The fastest way to generate all favicon sizes. It literally takes 2 seconds and handles the new manifest.json formats perfectly.": "تمام فیویکن سائز بنانے کا تیز ترین طریقہ۔ اس میں لفظی طور پر 2 سیکنڈ لگتے ہیں اور نئے manifest.json فارمیٹس کو بالکل ہینڈل کرتا ہے۔",
    "I used to use ImageMagick for this, but this site is so much simpler. Drag, drop, download, done.": "میں اس کے لیے ImageMagick استعمال کرتا تھا، لیکن یہ سائٹ بہت آسان ہے۔ گھسیٹیں، چھوڑیں، ڈاؤن لوڈ کریں، ہو گیا۔",
    "Love that it runs completely in the browser. I don't have to worry about uploading sensitive client logos to some random server.": "مجھے پسند ہے کہ یہ مکمل طور پر براؤزر میں چلتا ہے۔ مجھے حساس کلائنٹ کے لوگو کو کسی بے ترتیب سرور پر اپ لوڈ کرنے کی فکر کرنے کی ضرورت نہیں ہے۔",
    "Perfect for converting high-res PNGs to the legacy ICO format. A must-have tool for my daily web dev workflow.": "ہائی ریزولوشن PNGs کو پرانے ICO فارمیٹ میں تبدیل کرنے کے لیے بہترین ہے۔ میرے یومیہ ویب دیو ورک فلو کے لیے ایک لازمی ٹول۔",
    "Clean UI, fast processing, and it gives you the exact HTML tags to copy-paste. Excellent tool!": "کلین UI، تیز پروسیسنگ، اور یہ آپ کو کاپی پیسٹ کرنے کے لیے درست HTML ٹیگز دیتا ہے۔ بہترین ٹول!",
    "The transparency handling is spot on. Other converters usually mess up the alpha channels, but this one works perfectly.": "شفافیت سے نمٹنے کا طریقہ بالکل درست ہے۔ دوسرے کنورٹرز عام طور پر الفا چینلز کو گڑبڑ کرتے ہیں، لیکن یہ بالکل کام کرتا ہے۔",
    "Finally a favicon generator that includes the 512x512 PWA icon. Saves me from manually resizing images.": "آخر کار ایک فیویکن جنریٹر جس میں 512x512 PWA آئیکن شامل ہے۔ مجھے دستی طور پر تصاویر کا سائز تبدیل کرنے سے بچاتا ہے۔",
    "Simple and effective. The dark mode interface is a nice touch for us developers working late at night.": "سادہ اور موثر۔ ڈارک موڈ انٹرفیس ہم ڈویلپرز کے لیے ایک اچھا ٹچ ہے جو رات گئے کام کر رہے ہیں۔",
    "I've bookmarked this. It's the only favicon tool I've found that doesn't bombard you with ads or popups.": "میں نے اسے بک مارک کر لیا ہے۔ یہ واحد فیویکن ٹول ہے جو مجھے ملا ہے جو آپ پر اشتہارات یا پاپ اپس کی بمباری نہیں کرتا ہے۔",
    "Generates crisp 16x16 icons without blurring. The resizing algorithm they use is definitely high quality.": "دھندلا کیے بغیر کرکرا 16x16 آئیکنز تیار کرتا ہے۔ ان کا استعمال کرنے والا نیا سائز دینے والا الگورتھم یقینی طور پر اعلیٰ معیار کا ہے۔",
    "As a UX designer, I appreciate tools that just work. The drag and drop zone is huge and responsive.": "UX ڈیزائنر کے طور پر، میں ان ٹولز کی تعریف کرتا ہوں جو صرف کام کرتے ہیں۔ ڈریگ اور ڈراپ زون بہت بڑا اور جوابدہ ہے۔",
    "Works flawlessly on my Mac. The generated zip file is perfectly structured. Highly recommended.": "میرے میک پر بے عیب کام کرتا ہے۔ تیار کردہ زپ فائل بالکل ساختہ ہے۔ انتہائی سفارش کی جاتی ہے.",
    "Frontend Developer": "فرنٹ اینڈ ڈویلپر",
    "Web Designer": "ویب ڈیزائنر",
    "Software Engineer": "سافٹ ویئر انجینئر",
    "UI/UX Designer": "UI/UX ڈیزائنر",
    "Full Stack Dev": "فل اسٹیک دیو",
    "Product Manager": "پروڈکٹ مینیجر",
    "Indie Hacker": "انڈی ہیکر",
    "Tech Lead": "ٹیک لیڈ"
  }
};

Object.keys(translations).forEach(lang => {
  const filePath = path.join(__dirname, lang, 'index.html');
  if (fs.existsSync(filePath)) {
    const html = fs.readFileSync(filePath, 'utf8');
    const dom = new JSDOM(html);
    const document = dom.window.document;
    const dict = translations[lang];

    // Replace text in all elements
    const walk = document.createTreeWalker(document.body, 4, null, false);
    let n;
    while ((n = walk.nextNode())) {
      const txt = n.nodeValue.trim();
      
      // Remove wrapping quotes for testimonials matching
      const txtUnquoted = txt.replace(/^"|"$/g, '');
      
      if (dict[txt]) {
        n.nodeValue = n.nodeValue.replace(txt, dict[txt]);
      } else if (dict[txtUnquoted]) {
        n.nodeValue = n.nodeValue.replace(txtUnquoted, dict[txtUnquoted]);
      } else if (txt === "Free forever" && n.parentNode && n.parentNode.innerHTML.includes("Free forever")) {
         n.nodeValue = n.nodeValue.replace("Free forever", dict["Free forever"]);
      }
    }
    
    // Specific fix for "Add this to your website's <head> tag:" which is mixed content
    document.querySelectorAll('p').forEach(p => {
      if (p.innerHTML.includes("Add this to your website's")) {
        const spanText = p.innerHTML;
        // Depending on language, replacing it differently, or just a simple regex to replace the string around <code>
        // For Arabic: أضف هذا إلى علامة <head> الخاصة بموقعك:
        // For German: Fügen Sie dies dem <head>-Tag Ihrer Website hinzu:
        // For Spanish: Añade esto a la etiqueta <head> de tu sitio web:
        // For French: Ajoutez ceci à la balise <head> de votre site Web :
        // For Indonesian: Tambahkan ini ke tag <head> situs web Anda:
        // For Portuguese: Adicione isso à tag <head> do seu site:
        // For Turkish: Bunu web sitenizin <head> etiketine ekleyin:
        // For Urdu: اسے اپنی ویب سائٹ کے <head> ٹیگ میں شامل کریں:
        
        let beforeTag = "";
        let afterTag = "";
        
        if (lang === 'ar') { beforeTag = "أضف هذا إلى علامة "; afterTag = " الخاصة بموقعك:"; }
        if (lang === 'de') { beforeTag = "Fügen Sie dies dem "; afterTag = "-Tag Ihrer Website hinzu:"; }
        if (lang === 'es') { beforeTag = "Añade esto a la etiqueta "; afterTag = " de tu sitio web:"; }
        if (lang === 'fr') { beforeTag = "Ajoutez ceci à la balise "; afterTag = " de votre site Web :"; }
        if (lang === 'id') { beforeTag = "Tambahkan ini ke tag "; afterTag = " situs web Anda:"; }
        if (lang === 'pt') { beforeTag = "Adicione isso à tag "; afterTag = " do seu site:"; }
        if (lang === 'tr') { beforeTag = "Bunu web sitenizin "; afterTag = " etiketine ekleyin:"; }
        if (lang === 'ur') { beforeTag = "اسے اپنی ویب سائٹ کے "; afterTag = " ٹیگ میں شامل کریں:"; }
        
        if (beforeTag) {
          p.innerHTML = `${beforeTag}<code>&lt;head&gt;</code>${afterTag}`;
        }
      }
    });

    fs.writeFileSync(filePath, dom.serialize(), 'utf8');
    console.log(`Fully translated ${lang}/index.html`);
  }
});
